/** Auto-generated by npm run generate:upanishad-covers — do not edit by hand. */
export const UPANISHAD_COVER_STEMS = new Set<string>([
  "aitareya",
  "brihadaranyaka",
  "chandogya",
  "katha",
  "mundaka",
  "prashna",
  "taittiriya",
]);
