/**
 * Complete Shankaracharya Bhashya Data
 * Exported from development database
 */

export const COMPLETE_SHANKARA_BHASHYA: {
  [verseNumber: number]: {
    [languageCode: string]: string;
  };
} = {
  2: {
    "devanagari": "कुर्वन्नेव निर्वर्तयन्नेव इह कर्माणि अग्निहोत्रादीनि जिजीविषेत् जीवितुमिच्छेत् शतं शतसङ्ख्याकाः समाः संवत्सरान् । तावद्धि पुरुषस्य परमायुर्निरूपितम् । तथा च प्राप्तानुवादेन यज्जिजीविषेच्छतं वर्षाणि तत्कुर्वन्नेव कर्माणीत्येतद्विधीयते । एवम् एवंप्रकारे त्वयि जिजीविषति नरे नरमात्राभिमानिनि इतः एतस्मादग्निहोत्रादीनि कर्माणि कुर्वतो वर्तमानात्प्रकारात् अन्यथा प्रकारान्तरं नास्ति, येन प्रकारेणाशुभं कर्म न लिप्यते ; कर्मणा न लिप्यस इत्यर्थः । अतः शास्त्रविहितानि कर्माण्यग्निहोत्रादीनि कुर्वन्नेव जिजीविषेत् ॥\n\nकथं पुनरिदमवगम्यते — पूर्वेण मन्त्रेण संन्यासिनो ज्ञाननिष्ठोक्ता, द्वितीयेन तदशक्तस्य कर्मनिष्ठेति ? उच्यते — ज्ञानकर्मणोर्विरोधं पर्वतवदकम्प्यं यथोक्तं न स्मरसि किम् ? इहाप्युक्तम् — यो हि जिजीविषेत्स कर्माणि कुर्वन्नेव इति ; 'ईशा वास्यमिदं सर्वम्', 'तेन त्यक्तेन भुञ्जीथाः मा गृधः कस्य स्विद्धनम्' इति च । 'न जीविते मरणे वा गृधिं कुर्वीतारण्यमियात् इति पदं ततो न पुनरेयात्' इति च संन्यासशासनात् । उभयोः फलभेदं च वक्ष्यति । 'इमौ द्वावेव पन्थानावनुनिष्क्रान्ततरौ भवतः क्रियापथश्चैव पुरस्तात्संन्यासश्च' ; तयोः संन्यास एवातिरेचयति — 'न्यास एवात्यरेचयत्' (तै. नारा. ७८) इति तैत्तिरीयके । 'द्वाविमावथ पन्थानौ यत्र वेदाः प्रतिष्ठिताः । प्रवृत्तिलक्षणो धर्मो निवृत्तिश्च विभाषितः' (मो. ध. २४१ । ६) इत्यादि पुत्राय विचार्य निश्चितमुक्तं व्यासेन वेदाचार्येण भगवता । विभागं चानयोः प्रदर्शयिष्यामः ॥",
    "english": "Kurvanneva = always performing. iha = here. karmāni = rites such as agnihotra. jijīviṣet = one should desire to live. śatam = one hundred in number. samāḥ = years. For thus much is known to be the maximum age of man.\n\nSince this is a mere iteration of an empirically known fact, what should be taken as enjoined here is that, if one should desire to live a hundred years, he should live only performing karma.\n\nevam = in this manner, in regard to you, nare i.e. when you live content to be a mere man. itaḥ i.e., from this present course of performing karma like agnihotra. A different course na asti = does not exist; in which course evil action does not stain; i.e., you do not get tainted by sin. Wherefore if one should desire for life, one should live throughout performing karma such as agnihotra prescribed by the śāstra.\n\nHow is it to be understood that the former verse assigns to a sannyāsin devotion to knowledge and the latter, only devotion to karma to one incapable of Self-realisation? We reply—Do you not remember the aforesaid antithesis between jñāna and karma which remains unshakable as a mountain?\n\nHere also the same has been expressly stated in verses 1 and 2—that he who seeks to live must perform karma and that he who does not, must give up all desire. The same conclusion may be arrived at from the following directions to sannyāsins—\"He should desire neither for life, nor for death; he should enter a forest. This is the law.\" \"He should not thence return\".\n\nThe difference in result between the two will also be pointed out later on. Another statement of the like import is: \"These two paths only appeared in the beginning—the path of activity and the path of withdrawal.\" Of these two, renunciation is higher, cf. Taittirīya Āraṇyaka: \"Renunciation alone excelled\". And Vyāsa, the great Vedic teacher, after much reflection, taught his son definitely as follows—\"The Vedas aim at inculcating these two paths—one termed the path of activity and the other, of renunciation.\"",
    "kannada": "ಕುರ್ವನ್ನೇವ ನಿರ್ವರ್ತಯನ್ನೇವ ಇಹ ಕರ್ಮಾಣಿ ಅಗ್ನಿಹೋತ್ರಾದೀನಿ ಜಿಜೀವಿಷೇತ್ ಜೀವಿತುಮಿಚ್ಛೇತ್ ಶತಂ ಶತಸಂಖ್ಯಾಕಾಃ ಸಮಾಃ ಸಂವತ್ಸರಾನ್ । ತಾವದ್ಧಿ ಪುರುಷಸ್ಯ ಪರಮಾಯುರ್ನಿರೂಪಿತಮ್ । ತಥಾ ಚ ಪ್ರಾಪ್ತಾನುವಾದೇನ ಯಜ್ಜಿಜೀವಿಷೇಚ್ಛತಂ ವರ್ಷಾಣಿ ತತ್ಕುರ್ವನ್ನೇವ ಕರ್ಮಾಣೀತ್ಯೇತದ್ವಿಧೀಯತೇ ।\n\nಏವಮ್ ಏವಂಪ್ರಕಾರೇ ತ್ವಯಿ ಜಿಜೀವಿಷತಿ ನರೇ ನರಮಾತ್ರಾಭಿಮಾನಿನಿ ಇತಃ ಏತಸ್ಮಾದಗ್ನಿಹೋತ್ರಾದೀನಿ ಕರ್ಮಾಣಿ ಕುರ್ವತೋ ವರ್ತಮಾನಾತ್ಪ್ರಕಾರಾತ್ ಅನ್ಯಥಾ ಪ್ರಕಾರಾಂತರಂ ನಾಸ್ತಿ, ಯೇನ ಪ್ರಕಾರೇಣಾಶುಭಂ ಕರ್ಮ ನ ಲಿಪ್ಯತೇ ; ಕರ್ಮಣಾ ನ ಲಿಪ್ಯಸ ಇತ್ಯರ್ಥಃ । ಅತಃ ಶಾಸ್ತ್ರವಿಹಿತಾನಿ ಕರ್ಮಾಣ್ಯಗ್ನಿಹೋತ್ರಾದೀನಿ ಕುರ್ವನ್ನೇವ ಜಿಜೀವಿಷೇತ್ ।\n\nಕಥಂ ಪುನರಿದಮವಗಮ್ಯತೇ — ಪೂರ್ವೇಣ ಮಂತ್ರೇಣ ಸಂನ್ಯಾಸಿನೋ ಜ್ಞಾನನಿಷ್ಠೋಕ್ತಾ, ದ್ವಿತೀಯೇನ ತದಶಕ್ತಸ್ಯ ಕರ್ಮನಿಷ್ಠೇತಿ ? ಉಚ್ಯತೇ — ಜ್ಞಾನಕರ್ಮಣೋರ್ವಿರೋಧಂ ಪರ್ವತವದಕಂಪ್ಯಂ ಯಥೋಕ್ತಂ ನ ಸ್ಮರಸಿ ಕಿಮ್ ? ಇಹಾಪ್ಯುಕ್ತಮ್ — ಯೋ ಹಿ ಜಿಜೀವಿಷೇತ್ಸ ಕರ್ಮಾಣಿ ಕುರ್ವನ್ನೇವ ಇತಿ ; 'ಈಶಾ ವಾಸ್ಯಮಿದಂ ಸರ್ವಮ್', 'ತೇನ ತ್ಯಕ್ತೇನ ಭುಂಜೀಥಾಃ ಮಾ ಗೃಧಃ ಕಸ್ಯ ಸ್ವಿದ್ಧನಮ್' ಇತಿ ಚ ।\n\n'ನ ಜೀವಿತೇ ಮರಣೇ ವಾ ಗೃಧಿಂ ಕುರ್ವೀತಾರಣ್ಯಮಿಯಾತ್ ಇತಿ ಪದಂ ತತೋ ನ ಪುನರೇಯಾತ್' ಇತಿ ಚ ಸಂನ್ಯಾಸಶಾಸನಾತ್ । ಉಭಯೋಃ ಫಲಭೇದಂ ಚ ವಕ್ಷ್ಯತಿ । 'ನ್ಯಾಸ ಏವಾತ್ಯರೇಚಯತ್' ಇತಿ ತೈತ್ತಿರೀಯಕೇ । 'ದ್ವಾವಿಮಾವಥ ಪಂಥಾನೌ ಯತ್ರ ವೇದಾಃ ಪ್ರತಿಷ್ಠಿತಾಃ । ಪ್ರವೃತ್ತಿಲಕ್ಷಣೋ ಧರ್ಮೋ ನಿವೃತ್ತಿಶ್ಚ ವಿಭಾಷಿತಃ' ಇತ್ಯಾದಿ ಪುತ್ರಾಯ ವಿಚಾರ್ಯ ನಿಶ್ಚಿತಮುಕ್ತಂ ವ್ಯಾಸೇನ ವೇದಾಚಾರ್ಯೇಣ ಭಗವತಾ । ವಿಭಾಗಂ ಚಾನಯೋಃ ಪ್ರದರ್ಶಯಿಷ್ಯಾಮಃ ॥",
    "tamil": "குர்வந்நேவ நிர்வர்தயந்நேவ இஹ கர்மாணி அக்³நிஹோத்ராதீ³நி ஜிஜீவிஷேத் ஜீவிதுமிச்சே²த் ஶதம் ஶதஸங்க்²யாகா: ஸமா: ஸம்வத்ஸராந் । தாவத்³தி⁴ புருஷஸ்ய பரமாயுர்நிரூபிதம் । ததா² ச ப்ராப்தாநுவாதே³ந யஜ்ஜிஜீவிஷேச்ச²தம் வர்ஷாணி தத்குர்வந்நேவ கர்மாணீத்யேதத்³விதீ⁴யதே ।\n\nஏவம் ஏவம்ப்ரகாரே த்வயி ஜிஜீவிஷதி நரே நரமாத்ராபி⁴மாநிநி இத: ஏதஸ்மாத³க்³நிஹோத்ராதீ³நி கர்மாணி குர்வதோ வர்தமாநாத்ப்ரகாராத் அந்யதா² ப்ரகாராந்தரம் நாஸ்தி, யேந ப்ரகாரேணாஶுப⁴ம் கர்ம ந லிப்யதே ; கர்மணா ந லிப்யஸ இத்யர்த²: । அத: ஶாஸ்த்ரவிஹிதாநி கர்மாண்யக்³நிஹோத்ராதீ³நி குர்வந்நேவ ஜிஜீவிஷேத் ।\n\nகத²ம் புநரித³மவக³ம்யதே — பூர்வேண மந்த்ரேண ஸம்ந்யாஸிநோ ஜ்ஞாநநிஷ்டோ²க்தா, த்³விதீயேந தத³ஶக்தஸ்ய கர்மநிஷ்டே²தி ? உச்யதே — ஜ்ஞாநகர்மணோர்விரோத⁴ம் பர்வதவத³கம்ப்யம் யதோ²க்தம் ந ஸ்மரஸி கிம் ?\n\n'ந்யாஸ ஏவாத்யரேசயத்' இதி தைத்திரீயகே । 'த்³வாவிமாவத² பந்தா²நௌ யத்ர வேதா³: ப்ரதிஷ்டி²தா: । ப்ரவ்ருத்திலக்ஷணோ த⁴ர்மோ நிவ்ருத்திஶ்ச விபா⁴ஷித:' இத்யாதி³ புத்ராய விசார்ய நிஶ்சிதமுக்தம் வ்யாஸேந வேதா³சார்யேண ப⁴க³வதா । விபா⁴க³ம் சாநயோ: ப்ரத³ர்ஶயிஷ்யாம: ॥",
    "telugu": "కుర్వన్నేవ నిర్వర్తయన్నేవ ఇహ కర్మాణి అగ్నిహోత్రాదీని జిజీవిషేత్ జీవితుమిచ్ఛేత్ శతం శతసఙ్ఖ్యాకాః సమాః సంవత్సరాన్ । తావద్ధి పురుషస్య పరమాయుర్నిరూపితమ్ । తథా చ ప్రాప్తానువాదేన యజ్జిజీవిషేచ్ఛతం వర్షాణి తత్కుర్వన్నేవ కర్మాణీత్యేతద్విధీయతే ।\n\nఎవమ్ ఎవంప్రకారే త్వయి జిజీవిషతి నరే నరమాత్రాభిమానిని ఇతః ఎతస్మాదగ్నిహోత్రాదీని కర్మాణి కుర్వతో వర్తమానాత్ప్రకారాత్ అన్యథా ప్రకారాన్తరం నాస్తి, యేన ప్రకారేణాశుభం కర్మ న లిప్యతే ; కర్మణా న లిప్యస ఇత్యర్థః । అతః శాస్త్రవిహితాని కర్మాణ్యగ్నిహోత్రాదీని కుర్వన్నేవ జిజీవిషేత్ ।\n\nకథం పునరిదమవగమ్యతే — పూర్వేణ మన్త్రేణ సంన్యాసినో జ్ఞాననిష్ఠోక్తా, ద్వితీయేన తదశక్తస్య కర్మనిష్ఠేతి ? ఉచ్యతే — జ్ఞానకర్మణోర్విరోధం పర్వతవదకమ్ప్యం యథోక్తం న స్మరసి కిమ్ ? ఇహాప్యుక్తమ్ — యో హి జిజీవిషేత్స కర్మాణి కుర్వన్నేవ ఇతి ; 'ఈశా వాస్యమిదం సర్వమ్', 'తేన త్యక్తేన భుఞ్జీథాః మా గృధః కస్య స్విద్ధనమ్' ఇతి చ ।\n\n'న్యాస ఎవాత్యరేచయత్' ఇతి తైత్తిరీయకే । 'ద్వావిమావథ పన్థానౌ యత్ర వేదాః ప్రతిష్ఠితాః । ప్రవృత్తిలక్షణో ధర్మో నివృత్తిశ్చ విభాషితః' ఇత్యాది పుత్రాయ విచార్య నిశ్చితముక్తం వ్యాసేన వేదాచార్యేణ భగవతా । విభాగం చానయోః ప్రదర్శయిష్యామః ॥"
  },
  3: {
    "devanagari": "असुर्याः परमात्मभावमद्वयमपेक्ष्य देवादयोऽप्यसुराः । तेषां च स्वभूता लोका असुर्याः नाम । नामशब्दोऽनर्थको निपातः । ते लोकाः कर्मफलानि लोक्यन्ते दृश्यन्ते भुज्यन्त इति जन्मानि । अन्धेन अदर्शनात्मकेनाज्ञानेन तमसा आवृताः आच्छादिताः । तान् स्थावरान्तान् , प्रेत्य त्यक्त्वेमं देहम् अभिगच्छन्ति यथाकर्म यथाश्रुतम् । ये के च आत्महनः आत्मानं घ्नन्तीत्यात्महनः । के ? ते जनाः येऽविद्वांसः । कथं ते आत्मानं नित्यं हिंसन्ति ? अविद्यादोषेण विद्यमानस्यात्मनस्तिरस्करणात् । विद्यमानस्यात्मनो यत्कार्यं फलमजरामरत्वादिसंवेदनादिलक्षणम् , तत् हतस्येव तिरोभूतं भवतीति प्राकृता अविद्वांसो जना आत्महन इत्युच्यन्ते । तेन ह्यात्महननदोषेण संसरन्ति ते ॥",
    "english": "Asuryāḥ = demoniacal. Compared with the one non-dual Self which is Brahman, even gods are asuras (non-gods). The worlds natural to them are called asuryāḥ (demoniacal) nāma. The word nāma is a mere expletive. te lokāḥ = those worlds; i.e., the results of karma—so called because they are seen and experienced—are births.\n\nandhena = blind; i.e., by darkness which is the nature of not seeing, i.e., by ignorance. āvṛtāḥ = covered; i.e., concealed. tān = those, ending with immovable beings. pretya = leaving, i.e., departing from this body. They attain those worlds according to their karma and learning.\n\nye ke ca ātmahanaḥ = those who slay the Self, i.e., slayers of the Self. Who are they? Those people who are ignorant. How do they continuously slay the Self which is eternal? By the defect of ignorance, they conceal the Self which exists.\n\nThe result of the existing Self, which is of the nature of realizing immortality and freedom from old age, becomes hidden as if slain—therefore, ignorant ordinary people are called slayers of the Self. By this sin of slaying the Self, they continue in saṃsāra (cycle of rebirth).",
    "kannada": "ಅಸುರ್ಯಾಃ ಪರಮಾತ್ಮಭಾವಮದ್ವಯಮಪೇಕ್ಷ್ಯ ದೇವಾದಯೋಽಪ್ಯಸುರಾಃ । ತೇಷಾಂ ಚ ಸ್ವಭೂತಾ ಲೋಕಾ ಅಸುರ್ಯಾಃ ನಾಮ । ನಾಮಶಬ್ದೋಽನರ್ಥಕೋ ನಿಪಾತಃ । ತೇ ಲೋಕಾಃ ಕರ್ಮಫಲಾನಿ ಲೋಕ್ಯಂತೇ ದೃಶ್ಯಂತೇ ಭುಜ್ಯಂತ ಇತಿ ಜನ್ಮಾನಿ । ಅಂಧೇನ ಅದರ್ಶನಾತ್ಮಕೇನಾಜ್ಞಾನೇನ ತಮಸಾ ಆವೃತಾಃ ಆಚ್ಛಾದಿತಾಃ । ತಾನ್ ಸ್ಥಾವರಾಂತಾನ್ , ಪ್ರೇತ್ಯ ತ್ಯಕ್ತ್ವೇಮಂ ದೇಹಮ್ ಅಭಿಗಚ್ಛಂತಿ ಯಥಾಕರ್ಮ ಯಥಾಶ್ರುತಮ್ ।\n\nಯೇ ಕೇ ಚ ಆತ್ಮಹನಃ ಆತ್ಮಾನಂ ಘ್ನಂತೀತ್ಯಾತ್ಮಹನಃ । ಕೇ ? ತೇ ಜನಾಃ ಯೇಽವಿದ್ವಾಂಸಃ । ಕಥಂ ತೇ ಆತ್ಮಾನಂ ನಿತ್ಯಂ ಹಿಂಸಂತಿ ? ಅವಿದ್ಯಾದೋಷೇಣ ವಿದ್ಯಮಾನಸ್ಯಾತ್ಮನಸ್ತಿರಸ್ಕರಣಾತ್ । ವಿದ್ಯಮಾನಸ್ಯಾತ್ಮನೋ ಯತ್ಕಾರ್ಯಂ ಫಲಮಜರಾಮರತ್ವಾದಿಸಂವೇದನಾದಿಲಕ್ಷಣಮ್ , ತತ್ ಹತಸ್ಯೇವ ತಿರೋಭೂತಂ ಭವತೀತಿ ಪ್ರಾಕೃತಾ ಅವಿದ್ವಾಂಸೋ ಜನಾ ಆತ್ಮಹನ ಇತ್ಯುಚ್ಯಂತೇ । ತೇನ ಹ್ಯಾತ್ಮಹನನದೋಷೇಣ ಸಂಸರಂತಿ ತೇ ॥",
    "tamil": "அஸுர்யா: பரமாத்மபா⁴வமத்³வயமபேக்ஷ்ய தே³வாத³யோ(அ)ப்யஸுரா: । தேஷாம் ச ஸ்வபூ⁴தா லோகா அஸுர்யா: நாம । நாமஶப்³தோ³(அ)நர்த²கோ நிபாத: । தே லோகா: கர்மப²லாநி லோக்யந்தே த்³ருஶ்யந்தே பு⁴ஜ்யந்த இதி ஜந்மாநி । அந்தே⁴ந அத³ர்ஶநாத்மகேநாஜ்ஞாநேந தமஸா ஆவ்ருதா: ஆச்சா²தி³தா: । தாந் ஸ்தா²வராந்தாந் , ப்ரேத்ய த்யக்த்வேமம் தே³ஹம் அபி⁴க³ச்ச²ந்தி யதா²கர்ம யதா²ஶ்ருதம் ।\n\nயே கே ச ஆத்மஹந: ஆத்மாநம் க்⁴நந்தீத்யாத்மஹந: । கே ? தே ஜநா: யே(அ)வித்³வாம்ஸ: । கத²ம் தே ஆத்மாநம் நித்யம் ஹிம்ஸந்தி ? அவித்³யாதோ³ஷேண வித்³யமாநஸ்யாத்மநஸ்திரஸ்கரணாத் । வித்³யமாநஸ்யாத்மநோ யத்கார்யம் ப²லமஜராமரத்வாதி³ஸம்வேத³நாதி³லக்ஷணம் , தத் ஹதஸ்யேவ திரோபூ⁴தம் ப⁴வதீதி ப்ராக்ருதா அவித்³வாம்ஸோ ஜநா ஆத்மஹந இத்யுச்யந்தே । தேந ஹ்யாத்மஹநநதோ³ஷேண ஸம்ஸரந்தி தே ॥",
    "telugu": "అసుర్యాః పరమాత్మభావమద్వయమపేక్ష్య దేవాదయోఽప్యసురాః । తేషాం చ స్వభూతా లోకా అసుర్యాః నామ । నామశబ్దోఽనర్థకో నిపాతః । తే లోకాః కర్మఫలాని లోక్యన్తే దృశ్యన్తే భుజ్యన్త ఇతి జన్మాని । అన్ధేన అదర్శనాత్మకేనాజ్ఞానేన తమసా ఆవృతాః ఆచ్ఛాదితాః । తాన్ స్థావరాన్తాన్ , ప్రేత్య త్యక్త్వేమం దేహమ్ అభిగచ్ఛన్తి యథాకర్మ యథాశ్రుతమ్ ।\n\nయే కే చ ఆత్మహనః ఆత్మానం ఘ్నన్తీత్యాత్మహనః । కే ? తే జనాః యేఽవిద్వాంసః । కథం తే ఆత్మానం నిత్యం హింసన్తి ? అవిద్యాదోషేణ విద్యమానస్యాత్మనస్తిరస్కరణాత్ । విద్యమానస్యాత్మనో యత్కార్యం ఫలమజరామరత్వాదిసంవేదనాదిలక్షణమ్ , తత్ హతస్యేవ తిరోభూతం భవతీతి ప్రాకృతా అవిద్వాంసో జనా ఆత్మహన ఇత్యుచ్యన్తే । తేన హ్యాత్మహననదోషేణ సంసరన్తి తే ॥"
  },
  4: {
    "devanagari": "अनेजत् न एजत् । एजृ कम्पने, कम्पनं स्वरूपप्रच्युतिः, तद्वर्जितमित्यर्थः । सदा एकरूपमित्यभिप्रायः । एकम् अद्वितीयं सर्वभूतेषु । मनसो जवीयः मनसोऽपि शीघ्रतरम् । कथं विरुध्यमानधर्माश्रयत्वमात्मनः — अनेजत् , एकं मनसो जवीयश्चेति ? न विरोधः ; निरस्तसर्वोपाधि स्वरूपापेक्षया औपाधिकधर्मापेक्षया च द्वेधा आत्मनो विशेषणात् । तत्र परमार्थस्वरूपापेक्षया अनेजदेकमिति स्थितम् । औपाधिकधर्मापेक्षया तु — मनोवृत्त्याधारो ह्यात्मा सङ्कल्पविकल्पलक्षणया । सा च सर्वत्र गच्छन्ती द्रुततरगमनाद्ब्रह्मलोकादिषु क्षणमात्रेणैव गच्छतीत्यतिशीघ्रा तद्व्यापारो मनसः । सा गत्वा च यत्र यत्र गच्छति तत्र तत्रात्मना पूर्वप्राप्तेनेवात्मचैतन्यं व्याप्तमनुभवतीति मनसो जवीय इत्यात्मा उपचर्यते । नैनत् देवाः देवाश्चक्षुरादीनि करणानि प्रकाशनाद्देवाः ; एनमात्मानं न आप्नुवन् नाप्ता भवन्ति पूर्वं गतमपि ; मनसोऽपि द्रुततरत्वात् । कथं तानि तद्विषयाणि भवन्ति ? न हि करणानि आत्मानं स्वविषयं कुर्वन्ति कदाचित् । पूर्वं गतमित्यप्यौपचारिकमेव पूर्वोक्तन्यायेन मनोगत्यपेक्षया प्राप्तं प्राप्तत्वेनावभासत इत्यर्थः । तद्धावतोऽन्यान् अत्येति तिष्ठत् — मनोवाग्बुद्धिप्राणादीनात्मानं प्राप्तुं धावतोऽप्यचेतना अन्यान्नानाविधान्तदाश्रयान् , तत् ब्रह्म आत्मचैतन्यं स्वात्मनि तिष्ठदेव अत्येति अतिक्रम्य गच्छतीव ; यतः तस्मात् मातरिश्वा मातरि अन्तरिक्षे श्वसिति वातीति मातरिश्वा वायुः प्राणः । स प्राणो जगतः प्राणभृतां क्रियाशक्तिरूप आत्मोपाधिभूतः आपः कर्माणि जन्तूनां विभक्तवान् मन्त्रान्तरोक्तेन न्यायेन — 'अग्निर्वाचं प्राविशद्' इत्यादिना ॥",
    "english": "anejat = does not shake. ekam = one. manasaḥ = than mind. javīyaḥ = faster. This Self, though unmoving, is faster than the mind. How can there be such contradictory characteristics in one and the same thing? We reply—There is no contradiction because the Self pervades everything. By virtue of Its all-pervadingness, even while being stationary, It appears to go faster than the mind.\n\nnaitat = this. devāḥ = the senses (organs). āpnuvan = cannot reach. pūrvam arṣat = ran ahead. It goes ahead of the senses; the senses cannot overtake It. The senses, though fast, cannot catch up with It even while running.\n\ntad dhāvataḥ anyān atyeti tiṣṭhat = standing still, It overtakes others running. tasmin = in It. apo = waters, i.e., the actions of living beings. mātariśvā = the cosmic wind, the vital breath. dadhāti = supports, i.e., places.\n\nThe meaning is that the Self, though absolutely motionless and one, appears as if moving and as if many due to the limiting adjuncts of the body and senses, just as the one sun appears as many when reflected in different waters.",
    "kannada": "ಅನೇಜತ್ ನ ಏಜತ್ ಏಜೃ ಕಂಪನೇ, ನ ಕಂಪತೇ ನಿಶ್ಚಲಮಿತ್ಯರ್ಥಃ । ಏಕಂ ಸರ್ವಭೂತೇಷು । ಮನಸಃ ಸಂಕಲ್ಪಾಧ್ಯವಸಾಯಲಕ್ಷಣಾತ್ ಜವೀಯಃ ಶೀಘ್ರತರಮ್ । ಮನಸಾ ಹಿ ಸಂಕಲ್ಪ್ಯಮಾನೋ ದೂರದೇಶೋಽಪಿ ದ್ರಷ್ಟುಮಿಷ್ಯತೇ; ತತ್ ಮನಸೋಽಪಿ ಪೂರ್ವಮೇವ ತತ್ರಾತ್ಮಭೂತತ್ವಾದ್ಗಮ್ಯತೇ । ಅತ ಏವ ನ ಏನತ್ ದೇವಾಃ ಆಪ್ನುವನ್ ಚಕ್ಷುರಾದಯೋಽಪಿ ಮನೋವೃತ್ತ್ಯನುಯಾಯಿನಃ ಪೂರ್ವಂ ಪ್ರಾಪ್ತಂ ತತ್ಪ್ರಾಪ್ತುಂ ನ ಶಕ್ನುವಂತಿ ಅರ್ಷತ್ ಪೂರ್ವಂ ಗಚ್ಛತ್ಯೇವ, ತಸ್ಮಾನ್ನ ತೇ ಆಪ್ನುವನ್ ಇತ್ಯರ್ಥಃ । ತತ್ ಆತ್ಮತತ್ತ್ವಂ ಧಾವತಃ ಧಾವನವ್ಯಾಪಾರವತಃ ಅನ್ಯಾನ್ ಸರ್ವಾನ್ ದೇವಾದೀನ್ ಅತ್ಯೇತಿ ಅತಿಕ್ರಾಮತಿ ಜಲವನ್ನಿಶ್ಚಲಂ ತಿಷ್ಠತ್ ಸತ್ । ತಸ್ಮಿನ್ ಸರ್ವಾತ್ಮಕೇ ಪರಮಾತ್ಮನಿ ವಿಯತಿ ವಾಯುವ್ಯಾಪಾರಾಧಾರಭೂತೇ ಅಪಃ ಕರ್ಮಾಣಿ ಅಪಾಂ ಸ್ಥಾನಾನಿ ಚ ಮಾತರಿಶ್ವಾ ವಾಯುಃ ದಧಾತಿ ಧಾರಯತಿ ಸರ್ವಪ್ರಾಣಭೃತಾಮಿತಿ ॥",
    "tamil": "அநேஜத் ந ஏஜத் ஏஜ்ரு கம்பநே, ந கம்பதே நிஶ்சலமித்யர்த²: । ஏகம் ஸர்வபூ⁴தேஷு । மநஸ: ஸங்கல்பாத்⁴யவஸாயலக்ஷணாத் ஜவீய: ஶீக்⁴ரதரம் । மநஸா ஹி ஸங்கல்ப்யமாநோ தூ³ரதே³ஶோ(அ)பி த்³ரஷ்டுமிஷ்யதே; தத் மநஸோ(அ)பி பூர்வமேவ தத்ராத்மபூ⁴தத்வாத்³க³ம்யதே । அத ஏவ ந ஏநத் தே³வா: ஆப்நுவந் சக்ஷுராத³யோ(அ)பி மநோவ்ருத்த்யநுயாயிந: பூர்வம் ப்ராப்தம் தத்ப்ராப்தும் ந ஶக்நுவந்தி அர்ஷத் பூர்வம் க³ச்ச²த்யேவ, தஸ்மாந்ந தே ஆப்நுவந் இத்யர்த²: । தத் ஆத்மதத்த்வம் தா⁴வத: தா⁴வநவ்யாபாரவத: அந்யாந் ஸர்வாந் தே³வாதீ³ந் அத்யேதி அதிக்ராமதி ஜலவந்நிஶ்சலம் திஷ்ட²த் ஸத் । தஸ்மிந் ஸர்வாத்மகே பரமாத்மநி வியதி வாயுவ்யாபாராதா⁴ரபூ⁴தே அப: கர்மாணி அபாம் ஸ்தா²நாநி ச மாதரிஶ்வா வாயு: த³தா⁴தி தா⁴ரயதி ஸர்வப்ராணப்⁴ருதாமிதி ॥",
    "telugu": "అనేజత్ న ఏజత్ ఏజృ కంపనే, న కంపతే నిశ్చలమిత్యర్థః । ఏకం సర్వభూతేషు । మనసః సంకల్పాధ్యవసాయలక్షణాత్ జవీయః శీఘ్రతరమ్ । మనసా హి సంకల్ప్యమానో దూరదేశోఽపి ద్రష్టుమిష్యతే; తత్ మనసోఽపి పూర్వమేవ తత్రాత్మభూతత్వాద్గమ్యతే । అత ఏవ న ఏనత్ దేవాః ఆప్నువన్ చక్షురాదయోఽపి మనోవృత్త్యనుయాయినః పూర్వం ప్రాప్తం తత్ప్రాప్తుం న శక్నువంతి అర్షత్ పూర్వం గచ్ఛత్యేవ, తస్మాన్న తే ఆప్నువన్ ఇత్యర్థః । తత్ ఆత్మతత్త్వం ధావతః ధావనవ్యాపారవతః అన్యాన్ సర్వాన్ దేవాదీన్ అత్యేతి అతిక్రామతి జలవన్నిశ్చలం తిష్ఠత్ సత్ । తస్మిన్ సర్వాత్మకే పరమాత్మని వియతి వాయువ్యాపారాధారభూతే అపః కర్మాణి అపాం స్థానాని చ మాతరిశ్వా వాయుః దధాతి ధారయతి సర్వప్రాణభృతామితి ॥"
  },
  5: {
    "devanagari": "तदेजति तत् आत्मतत्त्वमेजति चलतीव अविद्यादृष्टेः, तन्नैजति तदेव न चलति विद्यादृष्टेः, नित्यमेकरसमचलं सर्वगतं नभोवत्परमार्थदृष्टेः । तद्दूरे तत्परमात्मतत्त्वं दूरे अत्यन्तं विप्रकृष्टमिवाविदुषाम् — यत्कोटिशतैरपि वर्षाणां न प्राप्यते अविद्वद्भिः — ; तदन्तिके तदेव परमार्थात्मतत्त्वम् उ — उशब्दोऽवधारणार्थः, अन्तिके समीपे अत्यन्तं विदुषां सम्यग्दर्शिनाम् ; तेषामात्मैव हि तत् , आत्मनश्च न किञ्चिन्निकटतरमस्ति । तदन्तरस्य सर्वस्य — 'सर्वस्यान्तरं यदात्मा' (बृ. उ. ३ । ४ । १) इति श्रुतेः — अस्य सर्वस्य जगतो नामरूपकर्माख्यस्य अन्तर्भवति ब्रह्म । तदु सर्वस्यास्य बाह्यतः व्याप्नोद्विस्तृतं विभुत्वात् सर्ववत् ; अन्तर्बाह्यतश्च यत्परमाण्वाकाशवत्सर्वसूक्ष्मं निरन्तरं च — 'विज्ञानं घनं प्रज्ञानं घनम्' इत्यादिश्रुतिभ्यः (बृ. उ. ४ । ५ । १३) ॥",
    "english": "tad ejati = that moves. tan na ejati = that does not move. tad dūre = that is far. tad antike = that is near. tad antar asya sarvasya = that is within all this. tad u sarvasyāsya bāhyataḥ = that is also outside all this.\n\nHow can contradictory qualities like moving and not moving, far and near, within and without, co-exist in the Self? This is explained: From the standpoint of the ignorant, the Self appears to move because they perceive It through the limiting adjuncts of body and mind. But from the standpoint of reality, It does not move since It is all-pervading.\n\nIt is far for the ignorant who do not know It, even though they are always with It. It is near for the wise who know It. It is within all because It is the innermost Self of all. It is outside all because It transcends everything, being the ultimate reality that underlies all phenomena.",
    "kannada": "ತತ್ ಆತ್ಮತತ್ತ್ವಮ್ ಏಜತಿ ಚಲತೀವ ಅವಿದ್ವತ್ಪ್ರತ್ಯಯಗೋಚರಮ್ , ಸ್ವತಃ ತು ತನ್ನೈಜತಿ ನ ಚಲತಿ ನಿಶ್ಚಲಮೇವ ತತ್ । ತದ್ದೂರೇ ತದ್ವಂತಿಕೇ — ತದ್ದೂರೇ ತತ್ ಸಮೀಪೇ ಚ ಇತ್ಯರ್ಥಃ । ಅವಿದುಷಾಂ ದೂರೇ ವಿದುಷಾಂ ಸಮೀಪೇ । ತದಂತರಸ್ಯ ಸರ್ವಸ್ಯ — ಸರ್ವಸ್ಯಾಂತಃ ತತ್ , ಸರ್ವವ್ಯಾಪಕತ್ವಾತ್ । ತದು ಸರ್ವಸ್ಯಾಸ್ಯ ಬಾಹ್ಯತಃ — ಸರ್ವಸ್ಯ ಬಹಿಃ ತತ್ , ಅಸಂಗತ್ವಾದಾಕಾಶವತ್ । ಸರ್ವಾತ್ಮಕಮಿತ್ಯರ್ಥಃ ॥",
    "tamil": "தத் ஆத்மதத்த்வம் ஏஜதி சலதீவ அவித்³வத்ப்ரத்யயகோ³சரம் , ஸ்வத: து தந்நைஜதி ந சலதி நிஶ்சலமேவ தத் । தத்³தூ³ரே தத்³வந்திகே — தத்³தூ³ரே தத் ஸமீபே ச இத்யர்த²: । அவிது³ஷாம் தூ³ரே விது³ஷாம் ஸமீபே । தத³ந்தரஸ்ய ஸர்வஸ்ய — ஸர்வஸ்யாந்த: தத் , ஸர்வவ்யாபகத்வாத் । தது³ ஸர்வஸ்யாஸ்ய பா³ஹ்யத: — ஸர்வஸ்ய ப³ஹி: தத் , அஸங்க³த்வாதா³காஶவத் । ஸர்வாத்மகமித்யர்த²: ॥",
    "telugu": "తత్ ఆత్మతత్త్వమ్ ఏజతి చలతీవ అవిద్వత్ప్రత్యయగోచరమ్ , స్వతః తు తన్నైజతి న చలతి నిశ్చలమేవ తత్ । తద్దూరే తద్వంతికే — తద్దూరే తత్ సమీపే చ ఇత్యర్థః । అవిదుషాం దూరే విదుషాం సమీపే । తదంతరస్య సర్వస్య — సర్వస్యాంతః తత్ , సర్వవ్యాపకత్వాత్ । తదు సర్వస్యాస్య బాహ్యతః — సర్వస్య బహిః తత్ , అసంగత్వాదాకాశవత్ । సర్వాత్మకమిత్యర్థః ॥"
  },
  6: {
    "devanagari": "यस्तु सम्यग्दर्शी सन् सर्वाणि भूतानि प्रकृत्यादिस्थावरान्तानि आत्मन्येव अनुपश्यति आत्मव्यतिरेकेण न पश्यति — 'आत्मा वा इदमेक एवाग्र आसीत्' (ऐ. उ. १ । १ । १) 'एक एवाद्वितीयो ब्रह्म' (छा. उ. ६ । २ । १) इत्यादिमन्त्रवर्णानुसारेण — सर्वभूतेषु च तान्येव आत्मानं पश्यति सर्वभूतेष्वात्मानं पश्यतीत्येतत् — 'यथोदकं शुद्धे शुद्धमासिक्तं तादृगेव भवति । एवं मुनेर्विजानत आत्मा भवति गौतम' (क. उ. २ । ४ । १५) इत्युक्तन्यायेन सर्वभूतात्मा हि स आत्मवित् । ततः ततो दर्शनात् न विजुगुप्सते न जुगुप्सां करोति । अन्यस्माद्धि वस्तुनो जुगुप्सितात्सर्वोऽपि जुगुप्सते । यदा तु आत्मैवेदं सर्वं परिशुद्धं ब्रह्म पश्यति, ततो न विजुगुप्सितं किञ्चित् । अतो न विजुगुप्सत इत्यनुवादः क्रियते ॥",
    "english": "yas tu sarvāṇi bhūtāni = whoever sees all beings. ātmani eva = in the Self alone. anupaśyati = sees, perceives. sarva-bhūteṣu ca ātmānam = and the Self in all beings. tataḥ = from that vision. na vijugupsate = does not hate, feel aversion.\n\nThis verse describes the vision of the knower of Self. One who sees all beings—from Brahma to a blade of grass—as existing in one's own Self, and also sees one's own Self in all beings, from such a vision does not feel aversion or hatred.\n\nThe reasoning is that hatred arises from the perception of something other than oneself that is undesirable. But when one sees only the Self everywhere, there is no \"other\" to hate. The vision of non-duality eliminates the very basis of aversion. This is the fruit of Self-knowledge—the cessation of all negative emotions based on the false perception of duality.",
    "kannada": "ಯಸ್ತು ವಿದ್ವಾನ್ ಸರ್ವಾಣಿ ಭೂತಾನಿ ಆಬ್ರಹ್ಮಸ್ತಂಬಪರ್ಯಂತಾನಿ ಆತ್ಮನಿ ಏವ ಪರಮಾರ್ಥತೋ ನಿರ್ವಿಶೇಷೇ ಅದ್ವಯೇ ಅನುಪಶ್ಯತಿ ಜ್ಞಾತ್ವಾ ಸರ್ವಭೂತಸ್ಥಂ ಚ ಆತ್ಮಾನಂ ತತಃ ತಸ್ಮಾತ್ಪರಮಾರ್ಥಾತ್ಮದರ್ಶನಾತ್ ನ ವಿಜುಗುಪ್ಸತೇ ನ ಜುಗುಪ್ಸಾಂ ಕರ್ತುಮಿಚ್ಛತಿ । ಸರ್ವಭೂತಾತ್ಮೈಕತ್ವವಿಜ್ಞಾನಾಜ್ಜುಗುಪ್ಸಾಕಾರಣಾಭಾವಾತ್ , ಕುತೋ ವಿಜುಗುಪ್ಸಾ ತತ್ವದರ್ಶಿನಃ ॥",
    "tamil": "யஸ்து வித்³வாந் ஸர்வாணி பூ⁴தாநி ஆப்³ரஹ்மஸ்தம்ப³பர்யந்தாநி ஆத்மநி ஏவ பரமார்த²தோ நிர்விஶேஷே அத்³வயே அநுபஶ்யதி ஜ்ஞாத்வா ஸர்வபூ⁴தஸ்த²ம் ச ஆத்மாநம் தத: தஸ்மாத்பரமார்தா²த்மத³ர்ஶநாத் ந விஜுகு³ப்ஸதே ந ஜுகு³ப்ஸாம் கர்துமிச்ச²தி । ஸர்வபூ⁴தாத்மைகத்வவிஜ்ஞாநாஜ்ஜுகு³ப்ஸாகாரணாபா⁴வாத் , குதோ விஜுகு³ப்ஸா தத்வத³ர்ஶிந: ॥",
    "telugu": "యస్తు విద్వాన్ సర్వాణి భూతాని ఆబ్రహ్మస్తంబపర్యంతాని ఆత్మని ఏవ పరమార్థతో నిర్విశేషే అద్వయే అనుపశ్యతి జ్ఞాత్వా సర్వభూతస్థం చ ఆత్మానం తతః తస్మాత్పరమార్థాత్మదర్శనాత్ న విజుగుప్సతే న జుగుప్సాం కర్తుమిచ్ఛతి । సర్వభూతాత్మైకత్వవిజ్ఞానాజ్జుగుప్సాకారణాభావాత్ , కుతో విజుగుప్సా తత్వదర్శినః ॥"
  },
  7: {
    "devanagari": "यस्मिन् काले विद्वान् आत्मतत्त्वविद्वान् सर्वाणि भूतानि प्रकृत्यादिस्थावरान्तानि आत्मैवाभूत् आत्मा एवाभवत् तस्य विजानतः विज्ञातवतो ब्रह्मैकत्वदर्शिनः तत्र तस्मिन् काले को मोहः कः शोक एकत्वानुपश्यतः — अनेकत्वं हि पश्यतो मोहो भवति कामादिदोषमूलः, तज्जो रागद्वेषादिप्रभवः शोकः कारणात् सत्त्वात्सत्त्वेन वा वियोगजः ; न त्वेकत्वं पश्यतो रागादिनिमित्तौ मोहशोकौ स्याताम् ; परिशुद्धं हि ब्रह्मैकत्वमात्मनः पश्यति परमार्थदर्शी आकाशवत् , तत्र शोकमोहादि कारणं नास्तीति भावः । तृतीयेन पादेन अविद्याकृतं कामकर्माविद्यादि संसारबीजम् अविद्यालक्षणं मोहशोकादिकं तत्कार्यं च विद्वत्समीपात् अपगतं दर्शयता विद्वतः संसारोच्छित्तिः सकारणा प्रदर्शिता भवति ॥",
    "english": "yasmin sarvāṇi bhūtāni = in whom all beings. ātma eva abhūt vijānataḥ = have become the Self alone of the knower. tatra = there, in that state. ko mohaḥ = what delusion. kaḥ śokaḥ = what sorrow. ekatvam anupaśyataḥ = for one who perceives oneness.\n\nWhen all beings have become one's own Self, when a person knows that all beings are nothing but the Self—what delusion or sorrow can there be for such a seer of oneness?\n\nDelusion arises from the false perception of plurality, and sorrow comes from attachment to what is other than oneself. But when one realizes that there is nothing other than the Self, the very cause of delusion and sorrow is destroyed. This is the supreme fruit of Self-knowledge.",
    "kannada": "ಯಸ್ಮಿನ್ ಯಸ್ಮಿನ್ಕಾಲೇ ಸರ್ವಾಣಿ ಭೂತಾನಿ ಆತ್ಮೈವ ಅಭೂತ್ ವಿಜಾನತಃ ಸಮ್ಯಗ್ದರ್ಶಿನಃ, ತತ್ರ ತಸ್ಮಿನ್ಕಾಲೇ ಕೋ ಮೋಹಃ ಕಃ ಶೋಕ ಏಕತ್ವಮ್ ಅನುಪಶ್ಯತಃ ಏಕತ್ವಂ ಪಶ್ಯತಃ । ಮೋಹಶೋಕೌ ಹ್ಯವಿದ್ವತೋ ಭವತಃ, ಅನ್ಯತ್ವದರ್ಶನಾತ್ । ಅತಃ ಏಕತ್ವದರ್ಶನಾದ್ವಿದುಷಃ ಶೋಕಮೋಹಾದ್ಯಭಾವಃ ಇತಿ ॥",
    "tamil": "யஸ்மிந் யஸ்மிந்காலே ஸர்வாணி பூ⁴தாநி ஆத்மைவ அபூ⁴த் விஜாநத: ஸம்யக்³த³ர்ஶிந:, தத்ர தஸ்மிந்காலே கோ மோஹ: க: ஶோக ஏகத்வம் அநுபஶ்யத: ஏகத்வம் பஶ்யத: । மோஹஶோகௌ ஹ்யவித்³வதோ ப⁴வத:, அந்யத்வத³ர்ஶநாத் । அத: ஏகத்வத³ர்ஶநாத்³வித⁴ஷ: ஶோகமோஹாத்³யபா⁴வ: இதி ॥",
    "telugu": "యస్మిన్ యస్మిన్కాలే సర్వాణి భూతాని ఆత్మైవ అభూత్ విజానతః సమ్యగ్దర్శినః, తత్ర తస్మిన్కాలే కో మోహః కః శోక ఏకత్వమ్ అనుపశ్యతః ఏకత్వం పశ్యతః । మోహశోకౌ హ్యవిద్వతో భవతః, అన్యత్వదర్శనాత్ । అతః ఏకత్వదర్శనాద్విదుషః శోకమోహాద్యభావః ఇతి ॥"
  },
  8: {
    "devanagari": "स यथोक्तलक्षणो ज्ञाननिष्ठो मोक्षधर्मो यथोक्तलक्षणात्मतत्त्वदर्शननिष्ठोऽध्यात्मविद्ब्रह्मविद्वेदार्थविन्मुक्त इत्युच्यते । अत्र च ब्रह्मदर्शनमात्रात्सहकारिसाधननिरपेक्षात्मत्वाल्लोकान्तराप्राप्तिफललक्षणं मुक्तत्वम् ; संसारकारणानि कामकर्मादीनि मोहशोकादिसंसारकार्याण्यात्मैकत्वदर्शनादपगतानि ; ततश्च कारणकार्योभयापगमात् 'ब्रह्मैवाहमस्मि' इति ब्रह्मभाव एव मुक्तत्वम् , न लोकान्तरप्राप्तिरित्यर्थः । तथा वक्ष्यति — 'ब्रह्म वेद ब्रह्मैव भवति' (मु. उ. ३ । २ । ९) इति । तदेतदात्मतत्त्वविद्याफलमात्मैकत्वं विभूतियुक्तं प्रकाश्यते —\n\nस पर्यगात् परि समन्तात् अगात् अगच्छत् व्याप्नोदित्यर्थः । कथंभूतः सन् ? शुक्रं शुद्धम् अकायम् अशरीरमव्रणम् अच्छिद्रम् अस्नाविरं स्नाव्नां सिराणां वर्जितमिति सूक्ष्मशरीराभावं दर्शयति ; शुद्धं शुद्धमेव पुनर्वचनात् अविद्याप्रत्युपस्थापितकृतकादिदोषैरस्पृष्टं निष्कलमित्यर्थः ; अपापविद्धम् अपुण्यविद्धं च धर्मानुमृष्टम् । कविः क्रान्तदर्शी सर्वज्ञः मनीषी मनस ईषिता चेतयिता सर्वस्य जगतः । परिभूः सर्वेषां भूतानां परिभविता परिभूः सर्वोत्कृष्ट इत्यर्थः । स्वयम्भूः स्वयमेव भवति स्वात्मसद्भावे नान्यमपेक्षते न प्रकृतिः न सहकारि निमित्तान्तरं वा अपेक्षते इत्यर्थः । शाश्वतीभ्यः सनातनीभ्यः नित्याभ्यः समाभ्यः संवत्सराख्येभ्यः प्रजाभ्यः प्रकर्षेण जातेभ्यः अर्थान् कर्माणि कर्तव्यानि यथातथ्यतः तत्त्वतो न्याय्यतश्च यथायोग्यमर्थं व्यदधात् विहितवान् विभक्तवानित्यर्थः ॥",
    "english": "saḥ paryagāt = He went around, i.e., pervaded everywhere. śukram = bright, pure. akāyam = bodiless, without a gross body. avraṇam = without wound, without injury. asnāviram = without sinews, without subtle body. śuddham = pure. apāpaviddham = untouched by sin.\n\nkaviḥ = the seer, omniscient. manīṣī = the thinker, wise. paribhūḥ = all-surpassing, self-existent. svayambhūḥ = self-born, not born from another. yāthātathyataḥ = properly, according to their true nature. arthān = objects, meanings. vyadadhāt = ordained, distributed. śāśvatībhyaḥ samābhyaḥ = for eternal years.\n\nThis describes the nature of the Supreme Self who pervades everything. Though bodiless and pure, It is the omniscient seer who ordains all things according to their true nature for all eternity.",
    "kannada": "ಸಃ ಪೂರ್ವಮಂತ್ರೋಕ್ತ ಆತ್ಮಾ ಪರ್ಯಗಾತ್ ಸರ್ವತೋಽಗಮತ್ ಸರ್ವವ್ಯಾಪೀತ್ಯರ್ಥಃ, ಶುಕ್ರಂ ಶುದ್ಧಮ್ ಅಕಾಯಂ ಶರೀರವರ್ಜಿತಮ್ । ಅವ್ರಣಂ ವ್ರಣರಹಿತಮ್ ಅಸ್ನಾವಿರಂ ಸ್ನಾಯುವರ್ಜಿತಮ್ ಶುದ್ಧಮ್ ಅಪಾಪವಿದ್ಧಮ್ ಪಾಪೇನಾವಿದ್ಧಮ್ ಅನಾವಿದ್ಧಮ್ ಇತ್ಯೇತತ್ । ಕವಿಃ ಕ್ರಾಂತದರ್ಶೀ ಮನೀಷೀ ಮೇಧಾವೀ ಪರಿಭೂಃ ಸರ್ವೇಷಾಂ ಭೋಕ್ತೃ̈ಣಾಂ ಪಾರಯಿತೃತಯಾ ಪರಿತೋಽಭವತ್ ಸ್ವಯಂಭೂಃ ಸ್ವಯಮೇವ ಭವತಿ, ನ ಕೇನಚಿತ್ಕ್ರಿಯತೇ ಇತ್ಯರ್ಥಃ । ಸೋಽಯಮೀಶ್ವರ ಯಾಥಾತಥ್ಯತಃ ಯಥಾತತ್ತ್ವತ ಐಷಣಾದಿಸಂಸ್ಥಿತಾನ್ ಅರ್ಥಾನ್ ವ್ಯದಧಾತ್ ವಿಹಿತವಾನ್ ಶಾಶ್ವತೀಭ್ಯಃ ನಿತ್ಯಾಭ್ಯಃ ಸಮಾಭ್ಯಃ ಸಂವತ್ಸರೇಭ್ಯಃ ಪ್ರಜಾಪತಿಭ್ಯಃ ॥",
    "tamil": "ஸ: பூர்வமந்த்ரோக்த ஆத்மா பர்யகா³த் ஸர்வதோ(அ)க³மத் ஸர்வவ்யாபீத்யர்த²:, ஶுக்ரம் ஶுத்³த⁴ம் அகாயம் ஶரீரவர்ஜிதம் । அவ்ரணம் வ்ரணரஹிதம் அஸ்நாவிரம் ஸ்நாயுவர்ஜிதம் ஶுத்³த⁴ம் அபாபவித்³த⁴ம் பாபேநாவித்³த⁴ம் அநாவித்³த⁴ம் இத்யேதத் । கவி: க்ராந்தத³ர்ஶீ மநீஷீ மேதா⁴வீ பரிபூ⁴: ஸர்வேஷாம் போ⁴க்த்ரு̈ணாம் பாரயித்ருதயா பரிதோ(அ)ப⁴வத் ஸ்வயம்பூ⁴: ஸ்வயமேவ ப⁴வதி, ந கேநசித்க்ரியதே இத்யர்த²: । ஸோ(அ)யமீஶ்வர யாதா²தத்²யத: யதா²தத்த்வத ஐஷணாதி³ஸம்ஸ்தி²தாந் அர்தா²ந் வ்யத³தா⁴த் விஹிதவாந் ஶாஶ்வதீப்⁴ய: நித்யாப்⁴ய: ஸமாப்⁴ய: ஸம்வத்ஸரேப்⁴ய: ப்ரஜாபதிப்⁴ய: ॥",
    "telugu": "సః పూర్వమంత్రోక్త ఆత్మా పర్యగాత్ సర్వతోఽగమత్ సర్వవ్యాపీత్యర్థః, శుక్రం శుద్ధమ్ అకాయం శరీరవర్జితమ్ । అవ్రణం వ్రణరహితమ్ అస్నావిరం స్నాయువర్జితమ్ శుద్ధమ్ అపాపవిద్ధమ్ పాపేనావిద్ధమ్ అనావిద్ధమ్ ఇత్యేతత్ । కవిః క్రాంతదర్శీ మనీషీ మేధావీ పరిభూః సర్వేషాం భోక్తృ̈ణాం పారయితృతయా పరితోఽభవత్ స్వయంభూః స్వయమేవ భవతి, న కేనచిత్క్రియతే ఇత్యర్థః । సోఽయమీశ్వర యాథాతథ్యతః యథాతత్త్వత ఐషణాదిసంస్థితాన్ అర్థాన్ వ్యదధాత్ విహితవాన్ శాశ్వతీభ్యః నిత్యాభ్యః సమాభ్యః సంవత్సరేభ్యః ప్రజాపతిభ్యః ॥"
  },
  9: {
    "devanagari": "अन्धं तमः अविवेकजमज्ञानं प्रविशन्ति ते तस्य फलभूतं गर्भजन्मजरामरणादिलक्षणं संसारमनुभवन्तीत्यर्थः । के ? ये अविद्यां कर्म — विद्याया अन्या अविद्या तस्यां रताः निष्ठां गता इत्यर्थः । विद्या च अविद्या च विद्याविद्ये — विपरीते विद्या न विद्या अविद्येत्यर्थो गम्यते । सा च अविद्या कर्म ; 'विद्यां चाविद्यां च' (ई. उ. ११) इति मन्त्रान्तरेणाविरोधात् । कर्म च विद्यायाः विपर्ययः प्रसिद्धो लोके — विद्या ज्ञानं कर्म तदन्यत् इति विद्याकर्मणोर्भेदोपलब्धेः । ये तु विद्यायां ज्ञाने कर्मभ्यो निवृत्ताः सन्तः केवलायां रताः ते ततो भूय इव ते तमो भूयस्तरमन्धं तमः प्रविशन्ति ॥",
    "english": "andham tamaḥ praviśanti = they enter blinding darkness. ye avidyām upāsate = those who worship ignorance (ritualistic karma alone). tataḥ bhūya iva te tamaḥ = into greater darkness than that. ya u vidyāyām ratāḥ = those who are devoted to knowledge alone.\n\nThis verse warns against two extremes: those who pursue only ritualistic karma without knowledge, and those who pursue only theoretical knowledge without the purification that comes from karma.\n\nThose who worship avidyā (ignorance, meaning ritualistic karma alone without understanding) enter darkness—they do not attain liberation. But those who are exclusively devoted to vidyā (knowledge alone, without the preparatory disciplines) enter into even greater darkness, because they become proud of their learning and neglect the necessary ethical and spiritual disciplines.",
    "kannada": "ಅಂಧಂ ತಮಃ ಅಂಧಕಾರಮಯಂ ಪ್ರವಿಶಂತಿ ಯೇ ಅವಿದ್ಯಾಂ ಕರ್ಮ ; ಅನ್ಯಚ್ಚ ವಿದ್ಯಾಯಾಃ ಕರ್ಮಣಃ, ವಿದ್ಯಾಕರ್ಮಣೋರ್ಹಿ ವಿಭಾಗೋ ಲೋಕೇ । ಯದ್ವಿದ್ಯಾ-ಜ್ಞಾನಂ ಸಾ ವಿದ್ಯಾ, ಕರ್ಮಾಣ್ಯವಿದ್ಯೇತಿ ವಿದ್ಯಾಕರ್ಮಣೋರ್ವಿಭಾಗಃ । ತತ್ರ ಅವಿದ್ಯಾಂ ಕರ್ಮಣಿ ನಿಷ್ಠಾ ಯೇಷಾಂ ತೇ ಅವಿದ್ಯಾಮುಪಾಸತೇ । ತತೋ ಭೂಯ ಇವ ತೇ ತಮೋ ಯ ಉ ವಿದ್ಯಾಯಾಂ ರತಾಃ — ವಿದ್ಯಾಯಾಮೇವ ಕೇವಲಾಯಾಂ ರತಾಸ್ತಸ್ಮಾದಪ್ಯಧಿಕತರಮಂಧಂ ತಮಃ ಪ್ರವಿಶಂತೀತ್ಯರ್ಥಃ ॥",
    "tamil": "அந்த⁴ம் தம: அந்த⁴காரமயம் ப்ரவிஶந்தி யே அவித்³யாம் கர்ம ; அந்யச்ச வித்³யாயா: கர்மண:, வித்³யாகர்மணோர்ஹி விபா⁴கோ³ லோகே । யத்³வித்³யா-ஜ்ஞாநம் ஸா வித்³யா, கர்மாண்யவித்³யேதி வித்³யாகர்மணோர்விபா⁴க³: । தத்ர அவித்³யாம் கர்மணி நிஷ்டா² யேஷாம் தே அவித்³யாமுபாஸதே । ததோ பூ⁴ய இவ தே தமோ ய உ வித்³யாயாம் ரதா: — வித்³யாயாமேவ கேவலாயாம் ரதாஸ்தஸ்மாத³ப்யதி⁴கதரமந்த⁴ம் தம: ப்ரவிஶந்தீத்யர்த²: ॥",
    "telugu": "అంధం తమః అంధకారమయం ప్రవిశంతి యే అవిద్యాం కర్మ ; అన్యచ్చ విద్యాయాః కర్మణః, విద్యాకర్మణోర్హి విభాగో లోకే । యద్విద్యా-జ్ఞానం సా విద్యా, కర్మాణ్యవిద్యేతి విద్యాకర్మణోర్విభాగః । తత్ర అవిద్యాం కర్మణి నిష్ఠా యేషాం తే అవిద్యాముపాసతే । తతో భూయ ఇవ తే తమో య ఉ విద్యాయాం రతాః — విద్యాయామేవ కేవలాయాం రతాస్తస్మాదప్యధికతరమంధం తమః ప్రవిశంతీత్యర్థః ॥"
  },
  10: {
    "devanagari": "अन्यदेवाहुः विद्यया क्रियत इति ; अन्यदाहुः फलम् अविद्यया कर्मणा क्रियत इति । इति शुश्रुम धीराणां बुद्धिमतां ये नः तत् विद्याविद्ये विचचक्षिरे व्याख्यातवन्तः ॥",
    "english": "anyat eva āhuḥ vidyayā = different indeed they say is the result of knowledge. anyat āhuḥ avidyayā = different they say is the result of ignorance. iti śuśruma dhīrāṇām = thus we have heard from the wise. ye naḥ tat vicacakṣire = who have explained that to us.\n\nThe wise teachers have taught that the result of vidyā (knowledge) is different from the result of avidyā (karma). Through karma alone, one may attain heaven or higher worlds, but these are temporary. Through knowledge alone without proper preparation, one may not attain the highest goal.\n\nThe combination of both—karma for purification and knowledge for liberation—is necessary. This teaching has been received from the wise teachers who have properly explained this distinction.",
    "kannada": "ಅನ್ಯದೇವ ಫಲಮ್ ಆಹುಃ ವಿದ್ಯಯಾ ಕ್ರಿಯತ ಇತಿ, ಅನ್ಯತ್ಫಲಮ್ ಆಹುಃ ಅವಿದ್ಯಯಾ ಕ್ರಿಯತ ಇತಿ । ಇತಿ ಶುಶ್ರುಮ — ಏವಂ ಶ್ರುತವಂತೋ ವಯಮಿತ್ಯರ್ಥಃ । ಧೀರಾಣಾಂ ಮೇಧಾವಿನಾಮ್ , ಯೇ ನಃ ಅಸ್ಮಭ್ಯಂ ತತ್ ವಿದ್ಯಾವಿದ್ಯೇ ವಿಚಚಕ್ಷಿರೇ ವ್ಯಾಖ್ಯಾತವಂತಃ ॥",
    "tamil": "அந்யதே³வ ப²லம் ஆஹு: வித்³யயா க்ரியத இதி, அந்யத்ப²லம் ஆஹு: அவித்³யயா க்ரியத இதி । இதி ஶுஶ்ரும — ஏவம் ஶ்ருதவந்தோ வயமித்யர்த²: । தீ⁴ராணாம் மேதா⁴விநாம் , யே ந: அஸ்மப்⁴யம் தத் வித்³யாவித்³யே விசசக்ஷிரே வ்யாக்²யாதவந்த: ॥",
    "telugu": "అన్యదేవ ఫలమ్ ఆహుః విద్యయా క్రియత ఇతి, అన్యత్ఫలమ్ ఆహుః అవిద్యయా క్రియత ఇతి । ఇతి శుశ్రుమ — ఏవం శ్రుతవంతో వయమిత్యర్థః । ధీరాణాం మేధావినామ్ , యే నః అస్మభ్యం తత్ విద్యావిద్యే విచచక్షిరే వ్యాఖ్యాతవంతః ॥"
  },
  11: {
    "devanagari": "विद्यां च अविद्यां च विद्याविद्ये उभे एकेनात्मना यस्तद्वेद यो वेद उभयं सह एकेनात्मना युगपत् — देवतारूपस्यात्मनो ज्ञानं विद्या, देवताराधनादिकं कर्म तदाराधकस्य कर्तुः कर्तव्यम् अविद्या ; अविद्यया कर्मणा मृत्युं देवताबुद्ध्या स्वात्मानं प्राकृतं कर्मबुद्धिं च तीर्त्वा विद्यया देवताज्ञानेन देवतात्मभावं गमयति तत्समानफलं जयति अमृतं स्वर्गलोकस्थमश्नुते प्राप्नोति । न हि कर्मकारी मृत्युं तर्तुमर्हति न चामृतमश्नुते । न च देवताज्ञानी । सहोभयानुष्ठानादुभयं प्राप्यत इति मन्त्रार्थः ॥",
    "english": "vidyāṃ ca avidyāṃ ca = both knowledge and karma. yaḥ tat veda ubhayaṃ saha = who knows both of them together. avidyayā mṛtyuṃ tīrtvā = crossing over death by means of karma. vidyayā amṛtam aśnute = by knowledge attains immortality.\n\nThis verse teaches the proper synthesis: one should know both vidyā and avidyā. By avidyā (ritualistic karma performed as a means of purification), one crosses over death—meaning one overcomes the negative effects of past karma and purifies the mind. By vidyā (Self-knowledge), one attains immortality—liberation from the cycle of birth and death.\n\nThis is not a combination of karma and knowledge in the sense of mixing them, but rather a sequence: karma prepares the mind for knowledge, and knowledge leads to liberation. The two have different functions but work together toward the ultimate goal.",
    "kannada": "ವಿದ್ಯಾಂ ಚ ಅವಿದ್ಯಾಂ ಚ ಕರ್ಮ ಯಃ ತದ್ವೇದ ಉಭಯಂ ಸಹ ಏಕೇನಾತ್ಮನಾ, ಅಸೌ ಅವಿದ್ಯಯಾ ಕರ್ಮಣಾ ಮೃತ್ಯುಂ ಸ್ವಾಭಾವಿಕಂ ಕರ್ಮಬೋಧಂ ತೀರ್ತ್ವಾ ಅತೀತ್ಯ, ವಿದ್ಯಯಾ ದೇವತಾಜ್ಞಾನೇನ ಅಮೃತಮ್ ದೇವತಾತ್ಮಭಾವಮಶ್ನುತೇ ಪ್ರಾಪ್ನೋತಿ । ನ ಹಿ ಕರ್ಮ ಕುರ್ವಾಣೋ ಮೃತ್ಯುಂ ತರ್ತುಂ ಶಕ್ನೋತಿ, ಅಮೃತಂ ವಾಶ್ನುತೇ । ಕುರ್ವಾಣಶ್ಚ ವಿದ್ಯಯಾ ಸಹೈವಾಶ್ನುತೇ — ಇತ್ಯರ್ಥಃ ॥",
    "tamil": "வித்³யாம் ச அவித்³யாம் ச கர்ம ய: தத்³வேத³ உப⁴யம் ஸஹ ஏகேநாத்மநா, அஸௌ அவித்³யயா கர்மணா ம்ருத்யும் ஸ்வாபா⁴விகம் கர்மபோ³த⁴ம் தீர்த்வா அதீத்ய, வித்³யயா தே³வதாஜ்ஞாநேந அம்ருதம் தே³வதாத்மபா⁴வமஶ்நுதே ப்ராப்நோதி । ந ஹி கர்ம குர்வாணோ ம்ருத்யும் தர்தும் ஶக்நோதி, அம்ருதம் வாஶ்நுதே । குர்வாணஶ்ச வித்³யயா ஸஹைவாஶ்நுதே — இத்யர்த²: ॥",
    "telugu": "విద్యాం చ అవిద్యాం చ కర్మ యః తద్వేద ఉభయం సహ ఏకేనాత్మనా, అసౌ అవిద్యయా కర్మణా మృత్యుం స్వాభావికం కర్మబోధం తీర్త్వా అతీత్య, విద్యయా దేవతాజ్ఞానేన అమృతమ్ దేవతాత్మభావమశ్నుతే ప్రాప్నోతి । న హి కర్మ కుర్వాణో మృత్యుం తర్తుం శక్నోతి, అమృతం వాశ్నుతే । కుర్వాణశ్చ విద్యయా సహైవాశ్నుతే — ఇత్యర్థః ॥"
  },
  12: {
    "devanagari": "अन्धं तमः प्रविशन्ति ये असम्भूतिं प्रकृतिम् अव्याकृतम् उपासते । ततो भूय इव ते तमः ये उ सम्भूत्यां कार्ये रताः हिरण्यगर्भाख्ये कार्यब्रह्मणि रताः ॥",
    "english": "andham tamaḥ praviśanti = they enter blinding darkness. ye asambhūtim upāsate = those who worship non-becoming (the unmanifest Prakṛti). tataḥ bhūya iva te tamaḥ = into greater darkness than that. ya u sambhūtyām ratāḥ = those who are devoted to becoming (the manifest effects like Hiraṇyagarbha).\n\nThis verse parallels the earlier one about vidyā and avidyā, now applied to asambhūti (the unmanifest cause, Prakṛti) and sambhūti (the manifest effect, the cosmic deity Hiraṇyagarbha).\n\nThose who worship only the unmanifest enter darkness because they do not attain the highest goal. Those who worship only the manifest deity enter even greater darkness because they become attached to limited results. The synthesis of both is required for complete spiritual development.",
    "kannada": "ಅಂಧಂ ತಮಃ ಪ್ರವಿಶಂತಿ ಯೇ ಅಸಂಭೂತಿಂ ಪ್ರಕೃತಿಂ ಕಾರಣಮವ್ಯಾಕೃತಾಖ್ಯಮ್ ಉಪಾಸತೇ, ತತೋ ಭೂಯ ಇವ ತೇ ತಮೋ ಯೇ ಉ ಸಂಭೂತ್ಯಾಂ ಕಾರ್ಯಬ್ರಹ್ಮಣಿ ಹಿರಣ್ಯಗರ್ಭಾಖ್ಯೇ ರತಾಃ । ಕಸ್ಮಾತ್ ? — ಅವಿನಾಶಿನಿ ಹಿ ಅವ್ಯಾಕೃತೇ ರತೇ ವಿನಾಶಿನಿ ಕಾರ್ಯಬ್ರಹ್ಮಣಿ ಸ್ಥಿತಸ್ಯ ವಿನಾಶಂ ಗಚ್ಛತೀತ್ಯಧಿಕತರಂ ತಮಃ ತತ್ರಾಸಕ್ತಸ್ಯ ॥",
    "tamil": "அந்த⁴ம் தம: ப்ரவிஶந்தி யே அஸம்பூ⁴திம் ப்ரக்ருதிம் காரணமவ்யாக்ருதாக்²யம் உபாஸதே, ததோ பூ⁴ய இவ தே தமோ யே உ ஸம்பூ⁴த்யாம் கார்யப்³ரஹ்மணி ஹிரண்யக³ர்பா⁴க்²யே ரதா: । கஸ்மாத் ? — அவிநாஶிநி ஹி அவ்யாக்ருதே ரதே விநாஶிநி கார்யப்³ரஹ்மணி ஸ்தி²தஸ்ய விநாஶம் க³ச்ச²தீத்யதி⁴கதரம் தம: தத்ராஸக்தஸ்ய ॥",
    "telugu": "అంధం తమః ప్రవిశంతి యే అసంభూతిం ప్రకృతిం కారణమవ్యాకృతాఖ్యమ్ ఉపాసతే, తతో భూయ ఇవ తే తమో యే ఉ సంభూత్యాం కార్యబ్రహ్మణి హిరణ్యగర్భాఖ్యే రతాః । కస్మాత్ ? — అవినాశిని హి అవ్యాకృతే రతే వినాశిని కార్యబ్రహ్మణి స్థితస్య వినాశం గచ్ఛతీత్యధికతరం తమః తత్రాసక్తస్య ॥"
  },
  13: {
    "devanagari": "अन्यदेवाहुः सम्भवात् कार्यब्रह्मोपासनात् फलम् ; अन्यदाहुः फलम् असम्भवात् प्रकृत्युपासनात् ; इति शुश्रुम धीराणां मेधाविनां ये नः तत् विचचक्षिरे व्याख्यातवन्तः ॥",
    "english": "anyat eva āhuḥ sambhavāt = different indeed they say is the result of becoming. anyat āhuḥ asambhavāt = different they say is the result of non-becoming. iti śuśruma dhīrāṇām = thus we have heard from the wise. ye naḥ tat vicacakṣire = who have explained that to us.\n\nJust as with vidyā and avidyā, the wise teachers have explained that the results of worshipping sambhūti (the manifest cosmic deity) and asambhūti (the unmanifest Prakṛti) are different.\n\nThe worship of Hiraṇyagarbha leads to certain powers and attainments. The worship of Prakṛti leads to dissolution into the unmanifest at the time of cosmic dissolution. Neither alone leads to final liberation. The teaching received from the wise clarifies this distinction.",
    "kannada": "ಅನ್ಯದೇವ ಫಲಂ ಆಹುಃ ವಿದ್ವಾಂಸಃ ಸಂಭವಾತ್ ಹಿರಣ್ಯಗರ್ಭೋಪಾಸನಾತ್, ಅನ್ಯತ್ಫಲಂ ಆಹುಃ ಅಸಂಭವಾತ್ ಪ್ರಕೃತ್ಯುಪಾಸನಾತ್ । ಇತಿ ಶುಶ್ರುಮ ಧೀರಾಣಾಂ ಯೇ ನಸ್ತದ್ವಿಚಚಕ್ಷಿರೇ — ಪೂರ್ವವತ್ ॥",
    "tamil": "அந்யதே³வ ப²லம் ஆஹு: வித்³வாம்ஸ: ஸம்ப⁴வாத் ஹிரண்யக³ர்போ⁴பாஸநாத், அந்யத்ப²லம் ஆஹு: அஸம்ப⁴வாத் ப்ரக்ருத்யுபாஸநாத் । இதி ஶுஶ்ரும தீ⁴ராணாம் யே நஸ்தத்³விசசக்ஷிரே — பூர்வவத் ॥",
    "telugu": "అన్యదేవ ఫలం ఆహుః విద్వాంసః సంభవాత్ హిరణ్యగర్భోపాసనాత్, అన్యత్ఫలం ఆహుః అసంభవాత్ ప్రకృత్యుపాసనాత్ । ఇతి శుశ్రుమ ధీరాణాం యే నస్తద్విచచక్షిరే — పూర్వవత్ ॥"
  },
  14: {
    "devanagari": "सम्भूतिं च विनाशं च यस्तद्वेदोभयं सह । विनाशेन मृत्युं तीर्त्वा सम्भूत्यामृतमश्नुते ॥ सम्भूतिं च कार्यब्रह्म हिरण्यगर्भाख्यम् विनाशं च प्रकृतिम् असम्भूतिं वा तदुपासनसाधनम् — सुवर्णादिनाशवत्कारणेन नाशात् विनाशः — उभयं सह एकेनात्मना यो वेद ; स विनाशेन मृत्युं प्राकृतं कामकर्मादिलक्षणं तीर्त्वा सम्भूत्या कार्यब्रह्मोपासनेन तत्समानं फलमैश्वर्यादिलक्षणम् अमृतम् अश्नुते भजते । यथा पूर्वोक्तयोः विद्याविद्ययोः फलमुक्तम् , तथेह सम्भूत्यसम्भूत्योः फलमुक्तं भवति ॥",
    "english": "sambhūtiṃ ca vināśaṃ ca = both becoming and destruction. yaḥ tat veda ubhayaṃ saha = who knows both of them together. vināśena mṛtyuṃ tīrtvā = crossing over death by means of (worship of) destruction. sambhūtyā amṛtam aśnute = by (worship of) becoming attains immortality.\n\nBy understanding both the manifest (sambhūti) and the unmanifest (vināśa or asambhūti), one achieves the complete spiritual path. Through worship of the unmanifest (Prakṛti), one crosses over death—meaning one transcends ordinary mortality. Through worship of the manifest (Hiraṇyagarbha), one attains immortality—meaning one achieves the higher spiritual goals.\n\nThe combination of both forms of worship, properly understood and practiced, leads to the supreme attainment. This parallels the earlier teaching about vidyā and avidyā.",
    "kannada": "ಸಂಭೂತಿಂ ಚ ವಿನಾಶಂ ಚ ಯಸ್ತದ್ವೇದೋಭಯಂ ಸಹ — ಸಂಭೂತಿಂ ಕಾರ್ಯಬ್ರಹ್ಮ ಹಿರಣ್ಯಗರ್ಭಮ್ , ಅಸಂಭೂತಿಂ ಚ ವಿನಾಶಂ ಅವ್ಯಾಕೃತೋಪಾಸನಸಾಧನಂ ಹೇತುಭಾವಮಿತಿ ವಾ, ದ್ವಯೋಃ ಪ್ರತಿಪಾದಿತಯೋಃ ಮಧ್ಯೇ ವಿನಾಶಮ್ ಅಸಂಭೂತಿಮ್ — ಯಃ ತದ್ವೇದ ಉಭಯಂ ಸಹ । ವಿನಾಶೇನ ಅಸಂಭೂತ್ಯುಪಾಸನಯಾ ಮೃತ್ಯುಂ ತೀರ್ತ್ವಾ, ಸಂಭೂತ್ಯಾ ಕಾರ್ಯಬ್ರಹ್ಮೋಪಾಸನಯಾ ಅಮೃತಮಶ್ನುತೇ — ದೇವತಾತ್ಮಭಾವಮಿತಿ ಪೂರ್ವವತ್ ॥",
    "tamil": "ஸம்பூ⁴திம் ச விநாஶம் ச யஸ்தத்³வேதோ³ப⁴யம் ஸஹ — ஸம்பூ⁴திம் கார்யப்³ரஹ்ம ஹிரண்யக³ர்ப⁴ம் , அஸம்பூ⁴திம் ச விநாஶம் அவ்யாக்ருதோபாஸநஸாத⁴நம் ஹேதுபா⁴வமிதி வா, த்³வயோ: ப்ரதிபாதி³தயோ: மத்⁴யே விநாஶம் அஸம்பூ⁴திம் — ய: தத்³வேத³ உப⁴யம் ஸஹ । விநாஶேந அஸம்பூ⁴த்யுபாஸநயா ம்ருத்யும் தீர்த்வா, ஸம்பூ⁴த்யா கார்யப்³ரஹ்மோபாஸநயா அம்ருதமஶ்நுதே — தே³வதாத்மபா⁴வமிதி பூர்வவத் ॥",
    "telugu": "సంభూతిం చ వినాశం చ యస్తద్వేదోభయం సహ — సంభూతిం కార్యబ్రహ్మ హిరణ్యగర్భమ్ , అసంభూతిం చ వినాశం అవ్యాకృతోపాసనసాధనం హేతుభావమితి వా, ద్వయోః ప్రతిపాదితయోః మధ్యే వినాశమ్ అసంభూతిమ్ — యః తద్వేద ఉభయం సహ । వినాశేన అసంభూత్యుపాసనయా మృత్యుం తీర్త్వా, సంభూత్యా కార్యబ్రహ్మోపాసనయా అమృతమశ్నుతే — దేవతాత్మభావమితి పూర్వవత్ ॥"
  },
  15: {
    "devanagari": "हिरण्मयेन पात्रेण सत्यस्यापिहितं मुखम् । तत्त्वं पूषन्नपावृणु सत्यधर्माय दृष्टये ॥ सत्यं ब्रह्म हिरण्मयेन पात्रेण ज्योतिर्मयेन तेजसा अपिहितम् आच्छादितम् अस्य मुखं द्वारम् — तत् आविष्कुरु सत्यधर्मार्थम् — पूषन् पोषण हे पूषन् तत् त्वं अपावृणु अपसारय मुखमावृणोद्धि हिरण्मयं रूपं यत्तव — सत्यधर्माय सत्येन धर्मो यस्य तादृशाय मम दृष्टये अनुग्रहाय ॥",
    "english": "hiraṇmayena pātreṇa = by a golden vessel, by a brilliant covering. satyasya apihitam mukham = the face of Truth is covered. tat tvaṃ pūṣan apāvṛṇu = that you, O Pūṣan (the sun deity), uncover. satyadharmāya dṛṣṭaye = for the sake of seeing the law of Truth.\n\nThe meditator, at the time of death, prays to the sun deity to remove the covering that conceals the Truth. The sun's brilliant rays form a \"golden vessel\" that covers the face of the Supreme Truth (Brahman) residing in the solar orb.\n\nThe devotee prays: \"O Pūṣan, remove this covering so that I, who am devoted to Truth and righteousness (satyadharma), may behold the Truth—the Supreme Self that you conceal.\" This is the prayer of one who has practiced the upāsanā (meditation) described in the earlier verses and now seeks the final vision.",
    "kannada": "ಹಿರಣ್ಮಯೇನ ಪಾತ್ರೇಣ ಸತ್ಯಸ್ಯಾಪಿಹಿತಂ ಮುಖಮ್ — ಹಿರಣ್ಮಯೇನ ಪಾತ್ರೇಣ ಇವ ತಮಸಾ ಆವೃತಂ ಸತ್ಯಸ್ಯ ಬ್ರಹ್ಮಣಃ ಮುಖಂ ದ್ವಾರಮ್ । ತತ್ತ್ವಂ ಪೂಷನ್ನಪಾವೃಣು — ತತ್ತ್ವಂ ಹೇ ಪೂಷನ್ ಸತ್ಯಧರ್ಮಾರ್ಥಮಪಾವೃಣು ಅಪಸಾರಯೇತಿ । ಸತ್ಯಧರ್ಮಾಯ ದೃಷ್ಟಯೇ — ಸತ್ಯಧರ್ಮಪ್ರಾಪ್ತಯೇ, ದೃಷ್ಟಯೇ ದರ್ಶನಾಯ ಚ ॥",
    "tamil": "ஹிரண்மயேந பாத்ரேண ஸத்யஸ்யாபிஹிதம் முக²ம் — ஹிரண்மயேந பாத்ரேண இவ தமஸா ஆவ்ருதம் ஸத்யஸ்ய ப்³ரஹ்மண: முக²ம் த்³வாரம் । தத்த்வம் பூஷந்நபாவ்ருணு — தத்த்வம் ஹே பூஷந் ஸத்யத⁴ர்மார்த²மபாவ்ருணு அபஸாரயேதி । ஸத்யத⁴ர்மாய த்³ருஷ்டயே — ஸத்யத⁴ர்மப்ராப்தயே, த்³ருஷ்டயே த³ர்ஶநாய ச ॥",
    "telugu": "హిరణ్మయేన పాత్రేణ సత్యస్యాపిహితం ముఖమ్ — హిరణ్మయేన పాత్రేణ ఇవ తమసా ఆవృతం సత్యస్య బ్రహ్మణః ముఖం ద్వారమ్ । తత్త్వం పూషన్నపావృణు — తత్త్వం హే పూషన్ సత్యధర్మార్థమపావృణు అపసారయేతి । సత్యధర్మాయ దృష్టయే — సత్యధర్మప్రాప్తయే, దృష్టయే దర్శనాయ చ ॥"
  },
  16: {
    "devanagari": "पूषन्नेकर्षे यम सूर्य प्राजापत्य व्यूह रश्मीन्समूह तेजः । यत्ते रूपं कल्याणतमं तत्ते पश्यामि योऽसावसौ पुरुषः सोऽहमस्मि ॥ पूषन् पोषणात् । एकर्षे एक ऋषिः गन्तासि त्वमेकोऽसीत्येकर्षे हे एकर्षे । यम सर्वस्य नियमनात् यमः । सूर्य रसानां स्वीकरणात् सूर्यः हे सूर्य । प्राजापत्य प्रजापतेः सूर्यापत्यं प्राजापत्यम् । व्यूह विगमय रश्मीन् समूह सञ्चिनु एकीकुरु तेजः ज्योतिः तव ; यत्ते तव रूपं कल्याणतमं तच्च ते तव पश्यामि अनुगृहाण द्रष्टुम् । यश्च असौ आदित्यमण्डले पुरुषः तत्स्थं ब्रह्म ; तं पुरुषम् अहम् अस्मि । स ब्रह्मात्मविद्ब्रह्मैव भवति ; 'ब्रह्म वेद ब्रह्मैव भवति' (मु. उ. ३ । २ । ९) इत्यादिश्रुतेः ॥",
    "english": "pūṣan ekarṣe = O Pūṣan, O sole seer. yama sūrya = O Yama (controller), O Sūrya (sun). prājāpatya = O son of Prajāpati. vyūha raśmīn = spread out, remove your rays. samūha tejaḥ = gather together your brilliance. yat te rūpaṃ kalyāṇatamaṃ tat te paśyāmi = that form of yours which is most auspicious, that I behold.\n\nThe devotee continues the prayer to the sun deity: \"O Pūṣan, the sole seer (because you witness all), O controller of all (Yama), O sun (Sūrya), O son of Prajāpati—please spread apart your rays, gather in your intense brilliance, so that I may behold your most auspicious form—the Supreme Self that resides within you.\"\n\nyoḥ asau puruṣaḥ = That person who is there (in the sun). so'ham asmi = I am He. This is the supreme realization: the identity between the individual self and the cosmic Self. The devotee realizes that the Puruṣa in the sun is identical with his own Self.",
    "kannada": "ಪೂಷನ್ನೇಕರ್ಷೇ ಯಮ ಸೂರ್ಯ ಪ್ರಾಜಾಪತ್ಯ ವ್ಯೂಹ ರಶ್ಮೀನ್ ಸಮೂಹ ತೇಜಃ — ಹೇ ಪೂಷನ್ ಪುಷ್ಟಿಕರಣಾತ್ , ಏಕರ್ಷೇ ಏಕ ಏವ ಋಷಿರ್ಗಚ್ಛತಿ ಸರ್ವಂ ಭುವನಂ ದರ್ಶಯನ್ ಇತ್ಯೇಕರ್ಷಿಃ, ಹೇ ಯಮ ಪ್ರಶಾಸಿತಃ, ಹೇ ಸೂರ್ಯ ರಸಾನಾಮಾದಾನಾತ್ , ಹೇ ಪ್ರಾಜಾಪತ್ಯ ಪ್ರಜಾಪತೇರಪತ್ಯ, ವ್ಯೂಹ ವಿಗಮಯ ಅಪಸಾರಯ ರಶ್ಮೀನ್ ದೀಪ್ತೀಃ, ಸಮೂಹ ಏಕೀಕುರು ತೇಜಃ ದೇಹಕಾಂತಿಮ್ — ಸತ್ಯಸ್ಯಾತ್ಮನೋ ದರ್ಶನಾರ್ಥಮಿತ್ಯರ್ಥಃ । ಯತ್ತೇ ರೂಪಂ ಕಲ್ಯಾಣತಮಂ ತತ್ತೇ ಪಶ್ಯಾಮಿ — ಯಸ್ತೇ ದೇವಸ್ಯ ರೂಪಂ ಕಲ್ಯಾಣತಮಂ ಮಂಗಲತಮಮ್ , ತತ್ತೇ ತವ ಪಶ್ಯಾಮಿ । ಯೋಽಸಾವಸೌ ಪುರುಷಃ ಸೋಽಹಮಸ್ಮಿ — ಯಶ್ಚಾಸೌ ಆದಿತ್ಯಮಂಡಲಸ್ಥಃ ಪುರುಷಃ, ಸೋಽಹಮಸ್ಮಿ; ಬ್ರಹ್ಮಾತ್ಮೈಕತ್ವದರ್ಶನಂ ಪ್ರದರ್ಶ್ಯತೇ ॥",
    "tamil": "பூஷந்நேகர்ஷே யம ஸூர்ய ப்ராஜாபத்ய வ்யூஹ ரஶ்மீந் ஸமூஹ தேஜ: — ஹே பூஷந் புஷ்டிகரணாத் , ஏகர்ஷே ஏக ஏவ ருஷிர்க³ச்ச²தி ஸர்வம் பு⁴வநம் த³ர்ஶயந் இத்யேகர்ஷி:, ஹே யம ப்ரஶாஸித:, ஹே ஸூர்ய ரஸாநாமாதா³நாத் , ஹே ப்ராஜாபத்ய ப்ரஜாபதேரபத்ய, வ்யூஹ விக³மய அபஸாரய ரஶ்மீந் தீ³ப்தீ:, ஸமூஹ ஏகீகுரு தேஜ: தே³ஹகாந்திம் — ஸத்யஸ்யாத்மநோ த³ர்ஶநார்த²மித்யர்த²: । யத்தே ரூபம் கல்யாணதமம் தத்தே பஶ்யாமி — யஸ்தே தே³வஸ்ய ரூபம் கல்யாணதமம் மங்க³லதமம் , தத்தே தவ பஶ்யாமி । யோஸாவஸௌ புருஷ: ஸோஹமஸ்மி — யஶ்சாஸௌ ஆதி³த்யமண்ட³லஸ்த²: புருஷ:, ஸோஹமஸ்மி; ப்³ரஹ்மாத்மைகத்வத³ர்ஶநம் ப்ரத³ர்ஶ்யதே ॥",
    "telugu": "పూషన్నేకర్షే యమ సూర్య ప్రాజాపత్య వ్యూహ రశ్మీన్ సమూహ తేజః — హే పూషన్ పుష్టికరణాత్ , ఏకర్షే ఏక ఏవ ఋషిర్గచ్ఛతి సర్వం భువనం దర్శయన్ ఇత్యేకర్షిః, హే యమ ప్రశాసితః, హే సూర్య రసానామాదానాత్ , హే ప్రాజాపత్య ప్రజాపతేరపత్య, వ్యూహ విగమయ అపసారయ రశ్మీన్ దీప్తీః, సమూహ ఏకీకురు తేజః దేహకాంతిమ్ — సత్యస్యాత్మనో దర్శనార్థమిత్యర్థః । యత్తే రూపం కల్యాణతమం తత్తే పశ్యామి — యస్తే దేవస్య రూపం కల్యాణతమం మంగలతమమ్ , తత్తే తవ పశ్యామి । యోఽసావసౌ పురుషః సోఽహమస్మి — యశ్చాసౌ ఆదిత్యమండలస్థః పురుషః, సోఽహమస్మి; బ్రహ్మాత్మైకత్వదర్శనం ప్రదర్శ్యతే ॥"
  },
  17: {
    "devanagari": "वायुरनिलममृतमथेदं भस्मान्तं शरीरम् । ॐ क्रतो स्मर कृतं स्मर क्रतो स्मर कृतं स्मर ॥ वायुः अयं प्राणो यः शरीरे वर्तते सः अनिलम् अमृतं सर्वात्मकं सूत्रात्मानं वायुमागच्छतु इति मरणकाल उत्क्रामन्प्राणो वायुमात्मनि सम्पद्यताम् । अथ इदं शरीरं भस्मान्तं भस्म अन्तः अवसानमस्य भस्मभूतमेव अस्त्वित्यर्थः । ॐ इत्येतदक्षरं ब्रह्म वाच्यं वाचकं च — 'ॐ इत्येकाक्षरं ब्रह्म' (ग. उ. अ. भा.) इति श्रुतेः — ; तदुभयमपि ॐ इत्येतदेव ; स्मरणार्थं च ॐकारोच्चारणम् । हे क्रतो हे सङ्कल्पात्मक संकल्पस्य कर्ताऽसि बुद्धिर्हि सर्वकार्येषु पूर्वं संकल्पयतीति क्रतुः संकल्पात्मक सन् हे क्रतो हे मनः स्मर प्राप्तः कालोऽयमात्मनः, स्मृतमनुस्मर यत्त्वयात्मज्ञानम् उपचितम् । कृतं च स्मर कृतम् अनुष्ठितं ज्ञानोपयोगि कर्म स्मर । क्रतो स्मर कृतं स्मरेति द्विर्वचनं मरणकालाभिप्रायम् आदर द्योतयति ॥",
    "english": "vāyuḥ anilam amṛtam = may this breath merge into the immortal air. atha idam bhasmāntaṃ śarīram = and this body end in ashes. oṃ krato smara kṛtaṃ smara = Om, O will (mind), remember! Remember what has been done! krato smara kṛtaṃ smara = O will, remember! Remember what has been done!\n\nAt the time of death, the devotee prays: \"May this prāṇa (vital breath) which resides in the body merge with the immortal cosmic air (Vāyu, the Sūtrātman). May this body end in ashes (be cremated).\"\n\n\"Om\"—this syllable is Brahman, both as the signifier and the signified. Its utterance is for the purpose of remembrance.\n\n\"O Kratu (will, or mind—the faculty of intention)! Remember! Now is the time to remember the Self. Remember the knowledge you have accumulated. And remember what you have done (the karma performed).\"\n\nThe repetition \"krato smara kṛtaṃ smara\" emphasizes the critical importance of this final remembrance at the moment of death. This shows the deep reverence for this moment.",
    "kannada": "ವಾಯುರನಿಲಮಮೃತಮಥೇದಂ ಭಸ್ಮಾಂತಂ ಶರೀರಮ್ — ಅಯಂ ಪ್ರಾಣವಾಯುಃ ಸರ್ವವ್ಯಾಪಿನಮನಿಲಂ ವಾಯುಮಭಿಗಚ್ಛತು , ಅಥ ಇದಂ ಭಸ್ಮಾಂತಂ ಶರೀರಮ್ — ಭಸ್ಮಾವಸಾನಮ್ ಇದಂ ಶರೀರಮಸ್ತು ಇತ್ಯರ್ಥಃ । ಕ್ರತೋ ಸ್ಮರ ಕೃತಂ ಸ್ಮರ — ಹೇ ಕ್ರತೋ ಹೇ ಸಂಕಲ್ಪ, ಸ್ಮರ ಕೃತಂ ಕರ್ಮ ಸ್ಮರ ಕೃತಂ ಸ್ಮರ ಇತಿ ದ್ವಿರ್ವಚನಂ ಮರಣಸಾಮೀಪ್ಯೇಽತ್ಯಾದರಾರ್ಥಮ್ । ಅಗ್ನೇ ನಯ ಸುಪಥಾ ರಾಯೇ ಅಸ್ಮಾನ್ — ಹೇ ಅಗ್ನೇ ಅಗ್ರಣೀಃ, ನಯ ಸುಪಥಾ ಶೋಭನೇನ ಮಾರ್ಗೇಣ, ರಾಯೇ ಧನಾಯ ಫಲೋಪಭೋಗಾಯ, ಅಸ್ಮಾನ್ ಕರ್ಮಕೃತೋಽಸ್ಮಾನ್ನಯಸ್ವೇತ್ಯರ್ಥಃ । ವಿಶ್ವಾನಿ ದೇವ ವಯುನಾನಿ ವಿದ್ವಾನ್ — ವಿಶ್ವಾನಿ ಹೇ ದೇವ ವಯುನಾನಿ ಕರ್ಮಾಣಿ ವಿದ್ವಾನ್ ಜಾನನ್ ಸರ್ವಜ್ಞೋ ಹ್ಯಸಿ । ಯುಯೋಧ್ಯಸ್ಮಜ್ಜುಹುರಾಣಮೇನಃ — ಯುಯೋಧಿ ನಿಬರ್ಹಣ, ಅಸ್ಮತ್ತಃ ಅಸ್ಮತ್ತೋ ಜುಹುರಾಣಂ ವಂಚನಾಶೀಲಮ್ ಏನಃ ಪಾಪಮ್ । ಭೂಯಿಷ್ಠಾಂ ತೇ ನಮ ಉಕ್ತಿಂ ವಿಧೇಮ — ಬಹುತರಂ ಭೂಯಸ್ತರಂ ತೇ ತುಭ್ಯಂ ನಮಃ ನಮಸ್ಕಾರಮುಕ್ತಿಂ ವಚನಂ ವಿಧೇಮ ಕರವಾಮಹೇ ಇತ್ಯರ್ಥಃ ॥",
    "tamil": "வாயுரநிலமம்ருதமதே²த³ம் ப⁴ஸ்மாந்தம் ஶரீரம் — அயம் ப்ராணவாயு: ஸர்வவ்யாபிநமநிலம் வாயுமபி⁴க³ச்ச²து , அத² இத³ம் ப⁴ஸ்மாந்தம் ஶரீரம் — ப⁴ஸ்மாவஸாநம் இத³ம் ஶரீரமஸ்து இத்யர்த²: । க்ரதோ ஸ்மர க்ருதம் ஸ்மர — ஹே க்ரதோ ஹே ஸங்கல்ப, ஸ்மர க்ருதம் கர்ம ஸ்மர க்ருதம் ஸ்மர இதி த்³விர்வசநம் மரணஸாமீப்யேத்யாத³ரார்த²ம் । அக்³நே நய ஸுபதா² ராயே அஸ்மாந் — ஹே அக்³நே அக்³ரணீ:, நய ஸுபதா² ஶோப⁴நேந மார்கே³ண, ராயே த⁴நாய ப²லோபபோ⁴கா³ய, அஸ்மாந் கர்மக்ருதோஸ்மாந்நயஸ்வேத்யர்த²: । விஶ்வாநி தே³வ வயுநாநி வித்³வாந் — விஶ்வாநி ஹே தே³வ வயுநாநி கர்மாணி வித்³வாந் ஜாநந் ஸர்வஜ்ஞோ ஹ்யஸி । யுயோத்⁴யஸ்மஜ்ஜுஹுராணமேந: — யுயோதி⁴ நிப³ர்ஹண, அஸ்மத்த: அஸ்மத்தோ ஜுஹுராணம் வஞ்சநாஶீலம் ஏந: பாபம் । பூ⁴யிஷ்டா²ம் தே நம உக்திம் வித⁴ேம — ப³ஹுதரம் பூ⁴யஸ்தரம் தே துப்⁴யம் நம: நமஸ்காரமுக்திம் வசநம் வித⁴ேம கரவாமஹே இத்யர்த²: ॥",
    "telugu": "వాయురనిలమమృతమథేదం భస్మాంతం శరీరమ్ — అయం ప్రాణవాయుః సర్వవ్యాపినమనిలం వాయుమభిగచ్ఛతు , అథ ఇదం భస్మాంతం శరీరమ్ — భస్మావసానమ్ ఇదం శరీరమస్తు ఇత్యర్థః । క్రతో స్మర కృతం స్మర — హే క్రతో హే సంకల్ప, స్మర కృతం కర్మ స్మర కృతం స్మర ఇతి ద్విర్వచనం మరణసామీప్యేఽత్యాదరార్థమ్ । అగ్నే నయ సుపథా రాయే అస్మాన్ — హే అగ్నే అగ్రణీః, నయ సుపథా శోభనేన మార్గేణ, రాయే ధనాయ ఫలోపభోగాయ, అస్మాన్ కర్మకృతోఽస్మాన్నయస్వేత్యర్థః । విశ్వాని దేవ వయునాని విద్వాన్ — విశ్వాని హే దేవ వయునాని కర్మాణి విద్వాన్ జానన్ సర్వజ్ఞో హ్యసి । యుయోధ్యస్మజ్జుహురాణమేనః — యుయోధి నిబర్హణ, అస్మత్తః అస్మత్తో జుహురాణం వంచనాశీలమ్ ఏనః పాపమ్ । భూయిష్ఠాం తే నమ ఉక్తిం విధేమ — బహుతరం భూయస్తరం తే తుభ్యం నమః నమస్కారముక్తిం వచనం విధేమ కరవామహే ఇత్యర్థః ॥"
  },
  18: {
    "devanagari": "अग्ने नय सुपथा राये अस्मान्विश्वानि देव वयुनानि विद्वान् । युयोध्यस्मज्जुहुराणमेनो भूयिष्ठां ते नम उक्तिं विधेम ॥ हे अग्ने अग्रणी असि अतो वयुनानि कर्माणि सम्यक् विद्वान् सुपथा शोभनेन पथा राये धनाय कर्मफलोपभोगाय नय गमय अस्मान् । विश्वानि सर्वाणि हे देव वयुनानि प्रज्ञानानि विद्वान् वेत्सि त्वम् ; अतः तु युयोधि अस्मत् अस्मत्तोऽपगमय जुहुराणं कुटिलं वक्रं गतिमत् एनः पापम् ; भूयिष्ठां बहुतरां ते तुभ्यं नमः उक्तिं वचनं नमस्कारं विधेम करवाम इति ॥\n\nएवम् ईशावास्योपनिषद्व्याख्यानं समाप्तम् ॥\n\nशान्तिपाठः\n\nॐ पूर्णमदः पूर्णमिदं पूर्णात् पूर्णमुदच्यते । पूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
    "english": "agne naya supathā rāye asmān = O Agni (fire deity), lead us by the good path to prosperity. viśvāni deva vayunāni vidvān = O god, knowing all the ways. yuyodhi asmaj juhurāṇam enaḥ = remove from us crooked sin. bhūyiṣṭhāṃ te nama uktiṃ vidhema = we offer you the most abundant words of salutation.\n\nThis is the final prayer of the Upanishad. The devotee prays to Agni, who leads the way (because fire is the first deity in Vedic rituals and guides the soul after death).\n\n\"O Agni, you know all the paths (vayunāni)—lead us by the good path (supathā) to prosperity (rāye), i.e., to the enjoyment of the fruits of our karma. O god, you who know all—remove from us the crooked, deceitful sin (juhurāṇam enaḥ). We offer you the most abundant words of salutation (nama uktiṃ).\"\n\nThus ends the Īśāvāsyopaniṣad bhāṣya. Oṃ Pūrṇamadaḥ pūrṇamidam—That is complete, this is complete. From completeness comes completeness. Taking completeness from completeness, completeness alone remains. Oṃ Śāntiḥ Śāntiḥ Śāntiḥ.",
    "kannada": "ಅಗ್ನೇ ನಯ ಸುಪಥಾ ರಾಯೇ ಅಸ್ಮಾನ್ ವಿಶ್ವಾನಿ ದೇವ ವಯುನಾನಿ ವಿದ್ವಾನ್ । ಯುಯೋಧ್ಯಸ್ಮಜ್ಜುಹುರಾಣಮೇನಃ ಭೂಯಿಷ್ಠಾಂ ತೇ ನಮ ಉಕ್ತಿಂ ವಿಧೇಮ ॥ ಹೇ ಅಗ್ನೇ ಅಗ್ರಣೀಃ, ನಯ ಸುಪಥಾ ಶೋಭನೇನ ಮಾರ್ಗೇಣ, ರಾಯೇ ಧನಾಯ ಫಲೋಪಭೋಗಾಯ, ಅಸ್ಮಾನ್ ಕರ್ಮಕೃತೋಽಸ್ಮಾನ್ನಯಸ್ವೇತ್ಯರ್ಥಃ । ವಿಶ್ವಾನಿ ಹೇ ದೇವ ವಯುನಾನಿ ಕರ್ಮಾಣಿ ವಿದ್ವಾನ್ ಜಾನನ್ ಸರ್ವಜ್ಞೋ ಹ್ಯಸಿ । ಯುಯೋಧಿ ನಿಬರ್ಹಣ, ಅಸ್ಮತ್ತಃ ಅಸ್ಮತ್ತೋ ಜುಹುರಾಣಂ ವಂಚನಾಶೀಲಮ್ ಏನಃ ಪಾಪಮ್ । ಭೂಯಿಷ್ಠಾಂ ತೇ ನಮಉಕ್ತಿಂ ವಿಧೇಮ — ಬಹುತರಂ ಭೂಯಸ್ತರಂ ತೇ ತುಭ್ಯಂ ನಮಸ್ಕಾರಂ ವಚನಂ ವಿಧೇಮ ಕರವಾಮಹೇ ಇತ್ಯರ್ಥಃ । ಇತ್ಯೇಷೋಪನಿಷತ್ಸಮಾಪ್ತಾ ॥",
    "tamil": "அக்³நே நய ஸுபதா² ராயே அஸ்மாந் விஶ்வாநி தே³வ வயுநாநி வித்³வாந் । யுயோத்⁴யஸ்மஜ்ஜுஹுராணமேந: பூ⁴யிஷ்டா²ம் தே நம உக்திம் வித⁴ேம ॥ ஹே அக்³நே அக்³ரணீ:, நய ஸுபதா² ஶோப⁴நேந மார்கே³ண, ராயே த⁴நாய ப²லோபபோ⁴கா³ய, அஸ்மாந் கர்மக்ருதோஸ்மாந்நயஸ்வேத்யர்த²: । விஶ்வாநி ஹே தே³வ வயுநாநி கர்மாணி வித்³வாந் ஜாநந் ஸர்வஜ்ஞோ ஹ்யஸி । யுயோதி⁴ நிப³ர்ஹண, அஸ்மத்த: அஸ்மத்தோ ஜுஹுராணம் வஞ்சநாஶீலம் ஏந: பாபம் । பூ⁴யிஷ்டா²ம் தே நமஉக்திம் வித⁴ேம — ப³ஹுதரம் பூ⁴யஸ்தரம் தே துப்⁴யம் நமஸ்காரம் வசநம் வித⁴ேம கரவாமஹே இத்யர்த²: । இத்யேஷோபநிஷத்ஸமாப்தா ॥",
    "telugu": "అగ్నే నయ సుపథా రాయే అస్మాన్ విశ్వాని దేవ వయునాని విద్వాన్ । యుయోధ్యస్మజ్జుహురాణమేనః భూయిష్ఠాం తే నమ ఉక్తిం విధేమ ॥ హే అగ్నే అగ్రణీః, నయ సుపథా శోభనేన మార్గేణ, రాయే ధనాయ ఫలోపభోగాయ, అస్మాన్ కర్మకృతోఽస్మాన్నయస్వేత్యర్థః । విశ్వాని హే దేవ వయునాని కర్మాణి విద్వాన్ జానన్ సర్వజ్ఞో హ్యసి । యుయోధి నిబర్హణ, అస్మత్తః అస్మత్తో జుహురాణం వంచనాశీలమ్ ఏనః పాపమ్ । భూయిష్ఠాం తే నమఉక్తిం విధేమ — బహుతరం భూయస్తరం తే తుభ్యం నమస్కారం వచనం విధేమ కరవామహే ఇత్యర్థః । ఇత్యేషోపనిషత్సమాప్తా ॥"
  }
};
